//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_PARAMETER
    {
        public int ID_ACCO_PARA { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> ID_PARA { get; set; }
        public string VAL_ACCO_PARA { get; set; }
        public Nullable<bool> VIG_ACCO_PARA { get; set; }
    }
}
