//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AssistanceEntities : DbContext
    {
        public AssistanceEntities()
            : base("name=AssistanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<VER_SEND_MAIL_Result> VER_SEND_MAIL(string nUM_TYPE_DI, Nullable<System.DateTime> dAT_FING)
        {
            var nUM_TYPE_DIParameter = nUM_TYPE_DI != null ?
                new ObjectParameter("NUM_TYPE_DI", nUM_TYPE_DI) :
                new ObjectParameter("NUM_TYPE_DI", typeof(string));
    
            var dAT_FINGParameter = dAT_FING.HasValue ?
                new ObjectParameter("DAT_FING", dAT_FING) :
                new ObjectParameter("DAT_FING", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VER_SEND_MAIL_Result>("VER_SEND_MAIL", nUM_TYPE_DIParameter, dAT_FINGParameter);
        }
    }
}
