//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambioNotificacion
    {
        public int IdCambio { get; set; }
        public Nullable<int> IdTipoNotificacion { get; set; }
        public Nullable<int> idChangeRequest { get; set; }
        public Nullable<int> idDetail { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual CHANGE_REQUEST CHANGE_REQUEST { get; set; }
        public virtual TipoNotificacion TipoNotificacion { get; set; }
        public virtual CHANGE_DETAIL CHANGE_DETAIL { get; set; }
    }
}
