//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public CATEGORY()
        {
            this.DETAILS_TICKET = new HashSet<DETAILS_TICKET>();
        }
    
        public int ID_CATE { get; set; }
        public string NAM_CATE { get; set; }
        public string ACR_CATE { get; set; }
        public string ABR_CATE { get; set; }
        public string DES_CATE { get; set; }
        public Nullable<bool> VIG_CATE { get; set; }
        public Nullable<bool> DEF_CATE { get; set; }
        public Nullable<int> ID_CATE_PARE { get; set; }
        public Nullable<int> NIV_CATE { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public Nullable<int> ACCO_USR { get; set; }
        public Nullable<int> ID_TYPE_TICK { get; set; }
        public Nullable<int> IdTipoGestionCambio { get; set; }
        public Nullable<bool> AplicaTicketProblema { get; set; }
        public Nullable<bool> AplicaGestionActivos { get; set; }
        public Nullable<bool> FlagModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> IdSLADet { get; set; }
        public Nullable<bool> TieneTarea { get; set; }
        public Nullable<bool> AplicaNotificacion { get; set; }
    
        public virtual ICollection<DETAILS_TICKET> DETAILS_TICKET { get; set; }
    }
}
