//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANGE_APPROVED
    {
        public int id { get; set; }
        public Nullable<int> idChangeRequest { get; set; }
        public Nullable<int> idTypeRequest { get; set; }
        public Nullable<int> approvedby { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public int approver { get; set; }
        public string justificationChange { get; set; }
        public Nullable<bool> activeJustified { get; set; }
        public Nullable<System.DateTime> changeDate { get; set; }
        public Nullable<System.DateTime> dateActiveJustified { get; set; }
        public Nullable<int> activeToplan { get; set; }
        public Nullable<System.DateTime> dateActiveToplan { get; set; }
        public Nullable<bool> VisNoti { get; set; }
    
        public virtual CHANGE_REQUEST CHANGE_REQUEST { get; set; }
        public virtual CHANGE_TYPE_REQUEST CHANGE_TYPE_REQUEST { get; set; }
    }
}
