//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_SUSTAIN
    {
        public DELIVERY_SUSTAIN()
        {
            this.ATTACHED = new HashSet<ATTACHED>();
            this.REQUEST_EXPENSE = new HashSet<REQUEST_EXPENSE>();
        }
    
        public int ID_DELI_SUST { get; set; }
        public Nullable<int> ID_PERS_ENTI_ASSI { get; set; }
        public Nullable<int> ID_PERS_ENTI_APPR { get; set; }
        public Nullable<int> ID_TYPE_DELI_SUST { get; set; }
        public string DOC_NUMB { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string NAM_ANEX { get; set; }
        public string COIN { get; set; }
        public Nullable<decimal> DOC_AMOU { get; set; }
        public Nullable<decimal> DOC_REMA { get; set; }
        public Nullable<decimal> AMO_AVAI { get; set; }
        public string COD_ANEX { get; set; }
        public string DOC_STAT { get; set; }
        public Nullable<System.DateTime> DAT_REGI { get; set; }
        public Nullable<decimal> TYP_CHAN { get; set; }
        public string NUM_ACCO { get; set; }
        public Nullable<int> ID_STAT_DELI_SUST { get; set; }
        public Nullable<decimal> AMO_PREV { get; set; }
        public Nullable<int> ID_PREV { get; set; }
        public Nullable<decimal> AMO_AVAI_PREV { get; set; }
        public Nullable<bool> AMO_AVAI_ASSI { get; set; }
        public string NUM_CHEC { get; set; }
        public string NumeroPRC { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public Nullable<System.DateTime> CREATED_MAIL { get; set; }
    
        public virtual TYPE_DELI_SUST TYPE_DELI_SUST { get; set; }
        public virtual ICollection<ATTACHED> ATTACHED { get; set; }
        public virtual ICollection<REQUEST_EXPENSE> REQUEST_EXPENSE { get; set; }
    }
}
