//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_DOCUMENT_SALE
    {
        public int ID_DETA_DOCU_SALE { get; set; }
        public Nullable<int> ID_DOCU_SALE { get; set; }
        public Nullable<int> ID_ARTI { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string CODE { get; set; }
        public string DESC_DETA { get; set; }
        public Nullable<System.DateTime> DAT_INI_SUPP { get; set; }
        public Nullable<System.DateTime> DAT_END_SUPP { get; set; }
        public Nullable<decimal> HOURS { get; set; }
        public Nullable<decimal> ATTENDANCE_HOURS { get; set; }
        public Nullable<decimal> VTA_ME { get; set; }
        public Nullable<decimal> PCTE_VTA_ME { get; set; }
        public Nullable<decimal> COSTO_ME { get; set; }
        public Nullable<decimal> GASTO { get; set; }
        public string CODE_ARTI { get; set; }
        public Nullable<int> ID_MANU { get; set; }
        public Nullable<int> ID_COMM_MODE { get; set; }
        public Nullable<int> ID_MANU_MODE { get; set; }
        public Nullable<int> ID_ITEM_CATE { get; set; }
        public string SERIE { get; set; }
    
        public virtual DOCUMENT_SALE DOCUMENT_SALE { get; set; }
    }
}
