//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILS_TICKET
    {
        public DETAILS_TICKET()
        {
            this.ATTACHEDs = new HashSet<ATTACHED>();
        }
    
        public int ID_DETA_TICK { get; set; }
        public Nullable<int> ID_TICK { get; set; }
        public Nullable<int> ID_STAT { get; set; }
        public Nullable<int> ID_CLIE { get; set; }
        public Nullable<int> ID_QUEU { get; set; }
        public Nullable<int> ID_TICK_PARENT { get; set; }
        public Nullable<int> ID_TYPE_DETA_TICK { get; set; }
        public string COM_DETA_TICK { get; set; }
        public Nullable<System.DateTime> FEC_SCHE { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CREATE_DETA_INCI { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> MINUTES { get; set; }
        public Nullable<int> IND { get; set; }
        public Nullable<int> ID_STAT_SALE_OPP { get; set; }
        public Nullable<decimal> AMM_SALE_OPP { get; set; }
        public Nullable<decimal> PRO_SALE_OPP { get; set; }
        public Nullable<System.DateTime> FROM_TIME { get; set; }
        public Nullable<System.DateTime> TO_TIME { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public Nullable<System.DateTime> CREATED_MAIL { get; set; }
        public Nullable<System.DateTime> GET_DATE { get; set; }
        public Nullable<int> ID_ENTI_CREATED { get; set; }
        public Nullable<int> ID_ENTI_TRAN { get; set; }
        public Nullable<int> ID_REAS_SCHE { get; set; }
        public Nullable<System.DateTime> FEC_END_REAL { get; set; }
        public Nullable<bool> EsperaPorCliente { get; set; }
        public string Titulo { get; set; }
        public string DescripcionProblema { get; set; }
        public string SolucionAplicada { get; set; }
        public string Impactonegocio { get; set; }
        public string SolucionTemporal { get; set; }
        public string SolucionDefinitiva { get; set; }
        public Nullable<bool> Causa { get; set; }
        public string Porque2 { get; set; }
        public string Porque3 { get; set; }
        public string Porque4 { get; set; }
        public string Porque5 { get; set; }
        public Nullable<bool> PortalComent { get; set; }
        public Nullable<int> IdTipoResolucion { get; set; }
        public Nullable<int> IdRazon { get; set; }
        public Nullable<int> IdCategoria { get; set; }
    
        public virtual ICollection<ATTACHED> ATTACHEDs { get; set; }
        public virtual TICKET TICKET { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
