//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_CONTROL_TYPE
    {
        public DOCUMENT_CONTROL_TYPE()
        {
            this.DOCUMENT_CONTROL = new HashSet<DOCUMENT_CONTROL>();
        }
    
        public int ID_DOCU_CONT_TYPE { get; set; }
        public string NAM_DOCU_CONT_TYPE { get; set; }
        public string DESC_DOCU_CONT_TYPE { get; set; }
        public Nullable<bool> HAVE_SUB_TYPE { get; set; }
        public Nullable<bool> HAVE_SIDIGE { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual ICollection<DOCUMENT_CONTROL> DOCUMENT_CONTROL { get; set; }
    }
}
