//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_SALE
    {
        public DOCUMENT_SALE()
        {
            this.DETAIL_DOCUMENT_SALE = new HashSet<DETAIL_DOCUMENT_SALE>();
        }
    
        public int ID_DOCU_SALE { get; set; }
        public Nullable<int> ID_ENTI { get; set; }
        public Nullable<int> ID_TYPE_DOCU_SALE { get; set; }
        public Nullable<int> ID_STAT_DOCU_SALE { get; set; }
        public string NUM_DOCU_SALE { get; set; }
        public Nullable<System.DateTime> DAT_DOCU_SALE { get; set; }
        public Nullable<decimal> TIPO_CAMB { get; set; }
        public string SUM_DOCU_SALE { get; set; }
        public string MONEY { get; set; }
        public Nullable<int> ID_PERS_ENTI_VEND { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DAT_REGISTER { get; set; }
        public Nullable<int> ID_COMP { get; set; }
        public Nullable<int> ID_CTTS { get; set; }
        public Nullable<int> ID_COMP_END { get; set; }
        public Nullable<System.DateTime> EXP_DATE { get; set; }
        public string OS { get; set; }
        public Nullable<int> ID_PROJ { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public Nullable<System.DateTime> CREATED_MAIL { get; set; }
        public Nullable<decimal> TIPCAM { get; set; }
        public Nullable<decimal> SUBTOT { get; set; }
        public Nullable<decimal> TOTIMP { get; set; }
        public Nullable<decimal> TOTCOS { get; set; }
        public Nullable<int> SEND_MAIL_CONTAC { get; set; }
        public Nullable<int> ID_PERS_ENTI_PREV { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> FormaPago { get; set; }
        public Nullable<int> Impacto { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<double> HorasProgramadas { get; set; }
        public Nullable<double> AvanceReal { get; set; }
        public Nullable<double> HorasTrabajadas { get; set; }
        public Nullable<int> ID_PERS_ENTI_PM { get; set; }
        public Nullable<bool> AplicaIng { get; set; }
        public Nullable<System.DateTime> FechaLimitePM { get; set; }
        public Nullable<decimal> PCCotizado { get; set; }
        public Nullable<decimal> PCReal { get; set; }
        public Nullable<decimal> PCCotizadoCompra { get; set; }
        public Nullable<decimal> PCRealCompra { get; set; }
        public Nullable<decimal> PCCotizadoServicio { get; set; }
        public Nullable<decimal> PCRealServicio { get; set; }
        public Nullable<decimal> PrecioCosto { get; set; }
        public Nullable<decimal> CostoReal { get; set; }
        public Nullable<decimal> Soporte { get; set; }
        public Nullable<decimal> CostoHora { get; set; }
        public Nullable<decimal> Instalacion { get; set; }
        public Nullable<decimal> Capacitacion { get; set; }
        public Nullable<int> IdTipoProyecto { get; set; }
        public Nullable<double> Facturacion { get; set; }
        public Nullable<double> CantidadFacturada { get; set; }
        public Nullable<System.DateTime> FechaFacturacion { get; set; }
        public Nullable<int> UserIdModifica { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICA { get; set; }
        public Nullable<bool> AplicaCronograma { get; set; }
        public Nullable<int> DiasCronograma { get; set; }
        public Nullable<System.DateTime> FechaRegCronograma { get; set; }
        public Nullable<bool> EstadoSoporteED { get; set; }
        public Nullable<bool> EstadoSoporteFabricante { get; set; }
        public Nullable<System.DateTime> FechaCompromiso { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<bool> EstadoRenovacion { get; set; }
        public Nullable<int> EstadoTipoProyecto { get; set; }
        public Nullable<decimal> SaldoPorCobrar { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<int> EnvioCorreoNOC { get; set; }
        public Nullable<bool> EstadoInforme { get; set; }
        public Nullable<bool> AplicaInformeAveria { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdDescripcionProd { get; set; }
        public Nullable<int> IdTipoServicio { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdFrecuenciaED { get; set; }
        public Nullable<int> IdFrecuenciaFAB { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public string OC { get; set; }
        public Nullable<bool> FlagModifica { get; set; }
        public string NUMREA { get; set; }
    
        public virtual TYPE_DOCUMENT_SALE TYPE_DOCUMENT_SALE { get; set; }
        public virtual ICollection<DETAIL_DOCUMENT_SALE> DETAIL_DOCUMENT_SALE { get; set; }
    }
}
