//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaPortalUsuario
    {
        public int Id { get; set; }
        public Nullable<int> IdTicket { get; set; }
        public Nullable<int> IdDetalleTicket { get; set; }
        public Nullable<int> IdEstadoEncuesta { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public string Comentario { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
