//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaConfiguracion
    {
        public int IdEncuestaConfiguracion { get; set; }
        public Nullable<int> IdAcco { get; set; }
        public Nullable<int> NroEncuestas { get; set; }
        public Nullable<System.DateTime> FechaUltimaEnvio { get; set; }
        public Nullable<bool> EnvioAutomatico { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> EncuestasEnviadas { get; set; }
        public Nullable<bool> EnvioDiario { get; set; }
    }
}
