//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntityEntities : DbContext
    {
        public EntityEntities()
            : base("name=EntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLASS_ENTITY> CLASS_ENTITY { get; set; }
        public virtual DbSet<PERSON_CONTRACT> PERSON_CONTRACT { get; set; }
        public virtual DbSet<PERSON_ENTITY> PERSON_ENTITY { get; set; }
        public virtual DbSet<ACCOUNT_ENTITY> ACCOUNT_ENTITY { get; set; }
        public virtual DbSet<PERSON_CONTRACT_CHART> PERSON_CONTRACT_CHART { get; set; }
        public virtual DbSet<PERSON_LOCATION> PERSON_LOCATION { get; set; }
        public virtual DbSet<PERSON_NOTIFICATION> PERSON_NOTIFICATION { get; set; }
        public virtual DbSet<PERSON_ENTITY_NOTIFICATION> PERSON_ENTITY_NOTIFICATION { get; set; }
        public virtual DbSet<CHART> CHARTs { get; set; }
        public virtual DbSet<NAME_CHART> NAME_CHART { get; set; }
        public virtual DbSet<WORK_PERIOD> WORK_PERIOD { get; set; }
        public virtual DbSet<QUESTION> QUESTIONs { get; set; }
        public virtual DbSet<QUESTION_GROUP> QUESTION_GROUP { get; set; }
        public virtual DbSet<QUESTION_TICKET> QUESTION_TICKET { get; set; }
        public virtual DbSet<SURVEY_ACCOUNT_TYPE_TICKET> SURVEY_ACCOUNT_TYPE_TICKET { get; set; }
        public virtual DbSet<SURVEY_STATUS> SURVEY_STATUS { get; set; }
        public virtual DbSet<SURVEY_TICKET> SURVEY_TICKET { get; set; }
        public virtual DbSet<SURVEY_TICKET_ACTIVITY> SURVEY_TICKET_ACTIVITY { get; set; }
        public virtual DbSet<EncuestaConfiguracion> EncuestaConfiguracions { get; set; }
    
        public virtual ObjectResult<TA_UEN_CARGO_Result> TA_UEN_CARGO(Nullable<int> iD_ACCO)
        {
            var iD_ACCOParameter = iD_ACCO.HasValue ?
                new ObjectParameter("ID_ACCO", iD_ACCO) :
                new ObjectParameter("ID_ACCO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TA_UEN_CARGO_Result>("TA_UEN_CARGO", iD_ACCOParameter);
        }
    
        public virtual ObjectResult<TA_UEN_CARGO_Result> TA_UEN_CARGO1(Nullable<int> iD_ACCO)
        {
            var iD_ACCOParameter = iD_ACCO.HasValue ?
                new ObjectParameter("ID_ACCO", iD_ACCO) :
                new ObjectParameter("ID_ACCO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TA_UEN_CARGO_Result>("TA_UEN_CARGO1", iD_ACCOParameter);
        }
    
        public virtual ObjectResult<RH_ORGA_Result> RH_ORGA(Nullable<int> iD_PERS_ENTI)
        {
            var iD_PERS_ENTIParameter = iD_PERS_ENTI.HasValue ?
                new ObjectParameter("ID_PERS_ENTI", iD_PERS_ENTI) :
                new ObjectParameter("ID_PERS_ENTI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RH_ORGA_Result>("RH_ORGA", iD_PERS_ENTIParameter);
        }
    
        public virtual ObjectResult<EncuestaConfiguracionListar_Result> EncuestaConfiguracionListar(Nullable<int> idAcco, Nullable<int> nroEncuestas)
        {
            var idAccoParameter = idAcco.HasValue ?
                new ObjectParameter("IdAcco", idAcco) :
                new ObjectParameter("IdAcco", typeof(int));
    
            var nroEncuestasParameter = nroEncuestas.HasValue ?
                new ObjectParameter("NroEncuestas", nroEncuestas) :
                new ObjectParameter("NroEncuestas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EncuestaConfiguracionListar_Result>("EncuestaConfiguracionListar", idAccoParameter, nroEncuestasParameter);
        }
    
        public virtual int ActualizarFechaUltimaEnvio(Nullable<int> idEncuestaConfiguracion)
        {
            var idEncuestaConfiguracionParameter = idEncuestaConfiguracion.HasValue ?
                new ObjectParameter("IdEncuestaConfiguracion", idEncuestaConfiguracion) :
                new ObjectParameter("IdEncuestaConfiguracion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarFechaUltimaEnvio", idEncuestaConfiguracionParameter);
        }
    
        public virtual int EncuestaConfiguracionEnvioManual(Nullable<int> idEncuestaConfiguracion)
        {
            var idEncuestaConfiguracionParameter = idEncuestaConfiguracion.HasValue ?
                new ObjectParameter("IdEncuestaConfiguracion", idEncuestaConfiguracion) :
                new ObjectParameter("IdEncuestaConfiguracion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EncuestaConfiguracionEnvioManual", idEncuestaConfiguracionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ValidarFechaUltimaDeEnvio(Nullable<int> idEncuestaConfiguracion)
        {
            var idEncuestaConfiguracionParameter = idEncuestaConfiguracion.HasValue ?
                new ObjectParameter("IdEncuestaConfiguracion", idEncuestaConfiguracion) :
                new ObjectParameter("IdEncuestaConfiguracion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ValidarFechaUltimaDeEnvio", idEncuestaConfiguracionParameter);
        }
    }
}
