//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public LOCATION()
        {
            this.CHANGE_REQUEST = new HashSet<CHANGE_REQUEST>();
        }
    
        public int ID_LOCA { get; set; }
        public Nullable<int> ID_SITE { get; set; }
        public Nullable<int> ID_LOCA_PARENT { get; set; }
        public string NAM_LOCA { get; set; }
        public Nullable<bool> VIG_LOCA { get; set; }
        public Nullable<int> NIVEL { get; set; }
        public string COD_LOCA { get; set; }
        public Nullable<int> IdJefeLocacion { get; set; }
        public Nullable<int> IdAnalistaRemediacionHost { get; set; }
    
        public virtual SITE SITE { get; set; }
        public virtual ICollection<CHANGE_REQUEST> CHANGE_REQUEST { get; set; }
    }
}
