//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAME_CHART
    {
        public NAME_CHART()
        {
            this.CHARTs = new HashSet<CHART>();
        }
    
        public int ID_NAM_CHAR { get; set; }
        public string NAM_CHAR { get; set; }
        public string NAM_CHAR_ENGL { get; set; }
        public string NAM_CHAR_SPAN { get; set; }
        public Nullable<bool> VIG_CHAR { get; set; }
        public Nullable<int> ID_TYPE_CHAR { get; set; }
        public Nullable<bool> MANAGEMENT { get; set; }
        public string ICON { get; set; }
        public Nullable<bool> EDIT { get; set; }
    
        public virtual ICollection<CHART> CHARTs { get; set; }
    }
}
