//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_CONTRACT_CHART
    {
        public int ID_PERS_CONT { get; set; }
        public int ID_CHAR { get; set; }
        public Nullable<bool> VIG_CONT_CHAR { get; set; }
        public Nullable<bool> IS_CONTRACT { get; set; }
        public Nullable<System.DateTime> DAT_STAR { get; set; }
        public Nullable<System.DateTime> DAT_END { get; set; }
    }
}
