//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_LOCATION
    {
        public int ID_PERS_LOCA { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_LOCA { get; set; }
        public Nullable<System.DateTime> STAR_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> VIG_LOCA { get; set; }
        public Nullable<int> ID_LOCA_LAST { get; set; }
    
        public virtual PERSON_ENTITY PERSON_ENTITY { get; set; }
    }
}
