//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_CONTRACT
    {
        public int ID_PERS_CONT { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_COND_CONT { get; set; }
        public Nullable<System.DateTime> STAR_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> VIG_CONT { get; set; }
        public Nullable<int> ID_WORK_PERI { get; set; }
        public Nullable<bool> LAS_CONT { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> GROSS_SALARY { get; set; }
        public Nullable<int> ID_CARG_AREA { get; set; }
        public Nullable<int> ID_PERS_STAT { get; set; }
        public Nullable<int> ID_PERS_CONT_PARENT { get; set; }
        public Nullable<int> ID_PERS_LOCA { get; set; }
        public Nullable<int> ID_CHAR { get; set; }
        public Nullable<System.DateTime> DAT_REGI { get; set; }
        public Nullable<int> ID_INME_BOSS_LAST { get; set; }
        public Nullable<int> ID_CHAR_LAST { get; set; }
    
        public virtual PERSON_ENTITY PERSON_ENTITY { get; set; }
        public virtual WORK_PERIOD WORK_PERIOD { get; set; }
    }
}
