//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLA
    {
        public SLA()
        {
            this.TICKET = new HashSet<TICKET>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<int> ID_TYPE_TICK { get; set; }
    
        public virtual ICollection<TICKET> TICKET { get; set; }
    }
}
