//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY_TICKET
    {
        public SURVEY_TICKET()
        {
            this.QUESTION_TICKET = new HashSet<QUESTION_TICKET>();
            this.SURVEY_TICKET_ACTIVITY = new HashSet<SURVEY_TICKET_ACTIVITY>();
        }
    
        public int ID_SURV_TICK { get; set; }
        public Nullable<int> ID_SURV { get; set; }
        public Nullable<int> ID_TICK { get; set; }
        public Nullable<int> ID_SURV_STAT { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<bool> SEN_REPO { get; set; }
    
        public virtual ICollection<QUESTION_TICKET> QUESTION_TICKET { get; set; }
        public virtual SURVEY_STATUS SURVEY_STATUS { get; set; }
        public virtual ICollection<SURVEY_TICKET_ACTIVITY> SURVEY_TICKET_ACTIVITY { get; set; }
    }
}
