//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY_ACCOUNT_TYPE_TICKET
    {
        public int ID_SURV_ACCO_TYPE_TICK { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> ID_TYPE_TICK { get; set; }
        public Nullable<int> ID_SURV { get; set; }
        public Nullable<System.DateTime> DATE_FROM { get; set; }
        public Nullable<System.DateTime> DATE_TO { get; set; }
    }
}
