//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_DELI_SUST
    {
        public TYPE_DELI_SUST()
        {
            this.DELIVERY_SUSTAIN = new HashSet<DELIVERY_SUSTAIN>();
            this.REQUEST_EXPENSE = new HashSet<REQUEST_EXPENSE>();
        }
    
        public int ID_TYPE_DELI_SUST { get; set; }
        public string NAM_TYPE_DELI_SUST { get; set; }
        public string NAM_TYPE_DELI_SUST_SPAN { get; set; }
        public string DES_TYPE_DELI_SUST { get; set; }
        public Nullable<bool> VIG_TYPE_DELI_SUST { get; set; }
    
        public virtual ICollection<DELIVERY_SUSTAIN> DELIVERY_SUSTAIN { get; set; }
        public virtual ICollection<REQUEST_EXPENSE> REQUEST_EXPENSE { get; set; }
    }
}
