//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNotification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_PERIOD
    {
        public WORK_PERIOD()
        {
            this.PERSON_CONTRACT = new HashSet<PERSON_CONTRACT>();
        }
    
        public int ID_WORK_PERI { get; set; }
        public Nullable<int> ID_PERS_CONT { get; set; }
        public Nullable<System.DateTime> STAR_DATE { get; set; }
        public Nullable<System.DateTime> CESS_DATE { get; set; }
        public Nullable<int> ID_REAS_END { get; set; }
        public string NAM_ATTA { get; set; }
        public Nullable<bool> INDEFINITE { get; set; }
        public Nullable<int> TOTAL_YEAR { get; set; }
        public Nullable<int> TOTAL_MONTH { get; set; }
        public Nullable<int> TOTAL_DAY { get; set; }
    
        public virtual ICollection<PERSON_CONTRACT> PERSON_CONTRACT { get; set; }
    }
}
