//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electrodata.ERPElectrodata.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComCuentaCategoryTema
    {
        public int IdCuentaCategoryTema { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> ID_CATE { get; set; }
        public Nullable<int> IdTema { get; set; }
        public Nullable<bool> Vigencia { get; set; }
    
        public virtual ComTema ComTema { get; set; }
    }
}
