//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electrodata.ERPElectrodata.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComLeccionAprendida
    {
        public int IdLeccioNAprendida { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> ID_TICKET { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Nivel1 { get; set; }
        public Nullable<int> Nvel2 { get; set; }
        public Nullable<int> Nivel3 { get; set; }
        public Nullable<int> Nivel4 { get; set; }
        public Nullable<int> IdTema { get; set; }
        public Nullable<bool> VigLeccionAprendida { get; set; }
        public Nullable<int> NroRevisiones { get; set; }
        public string Puntuacion { get; set; }
        public string DescripcionProblema { get; set; }
        public string SolucionAplicada { get; set; }
        public string Impactonegocio { get; set; }
        public string SolucionTemporal { get; set; }
        public string SolucionDefinitiva { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public string UsuarioUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string EstadoAprobacion { get; set; }
        public string ColorEstado { get; set; }
        public Nullable<int> Aprobador { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idUsuarioUpdate { get; set; }
        public string Porque2 { get; set; }
        public string Porque3 { get; set; }
        public string Porque4 { get; set; }
        public string Porque5 { get; set; }
    }
}
