//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electrodata.ERPElectrodata.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComLogLeccionesAprendida
    {
        public int id { get; set; }
        public Nullable<int> idLeccioNAprendida { get; set; }
        public string Título { get; set; }
        public Nullable<int> idTema { get; set; }
        public Nullable<int> Revision { get; set; }
        public Nullable<int> Puntuacion { get; set; }
        public string EstadoAprobacion { get; set; }
        public string ColorEstado { get; set; }
        public Nullable<int> Aprobador { get; set; }
        public string usuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string accion { get; set; }
        public Nullable<int> declarado { get; set; }
        public Nullable<int> idusuario { get; set; }
    }
}
