//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electrodata.ERPElectrodata.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ECoreEntities : DbContext
    {
        public ECoreEntities()
            : base("name=ECoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATTACHED> ATTACHEDs { get; set; }
        public virtual DbSet<ComCuentaCategoryTema> ComCuentaCategoryTemas { get; set; }
        public virtual DbSet<ComLogLeccionesAprendida> ComLogLeccionesAprendidas { get; set; }
        public virtual DbSet<ComTema> ComTemas { get; set; }
        public virtual DbSet<TYPE_DOCUMENT_ATTACH> TYPE_DOCUMENT_ATTACH { get; set; }
        public virtual DbSet<Adjunto> Adjuntoes { get; set; }
        public virtual DbSet<GestionDocumento> GestionDocumentoes { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumentoes { get; set; }
        public virtual DbSet<CatalogoServicio> CatalogoServicios { get; set; }
        public virtual DbSet<ComLeccionAprendida> ComLeccionAprendidas { get; set; }
    
        public virtual ObjectResult<ComDetailLearnedLesson_Result> ComDetailLearnedLesson(Nullable<int> idLeccionAprendida)
        {
            var idLeccionAprendidaParameter = idLeccionAprendida.HasValue ?
                new ObjectParameter("idLeccionAprendida", idLeccionAprendida) :
                new ObjectParameter("idLeccionAprendida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComDetailLearnedLesson_Result>("ComDetailLearnedLesson", idLeccionAprendidaParameter);
        }
    
        public virtual ObjectResult<ComFindTopics_Result> ComFindTopics(string nomtema, Nullable<int> idCuenta, Nullable<int> idCategoria, string fechaCreacionInicio, string fechaCreacionFin, Nullable<int> vigtema, string fechaBajaInicio, string fechaBajaFin)
        {
            var nomtemaParameter = nomtema != null ?
                new ObjectParameter("Nomtema", nomtema) :
                new ObjectParameter("Nomtema", typeof(string));
    
            var idCuentaParameter = idCuenta.HasValue ?
                new ObjectParameter("idCuenta", idCuenta) :
                new ObjectParameter("idCuenta", typeof(int));
    
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            var fechaCreacionInicioParameter = fechaCreacionInicio != null ?
                new ObjectParameter("FechaCreacionInicio", fechaCreacionInicio) :
                new ObjectParameter("FechaCreacionInicio", typeof(string));
    
            var fechaCreacionFinParameter = fechaCreacionFin != null ?
                new ObjectParameter("FechaCreacionFin", fechaCreacionFin) :
                new ObjectParameter("FechaCreacionFin", typeof(string));
    
            var vigtemaParameter = vigtema.HasValue ?
                new ObjectParameter("Vigtema", vigtema) :
                new ObjectParameter("Vigtema", typeof(int));
    
            var fechaBajaInicioParameter = fechaBajaInicio != null ?
                new ObjectParameter("FechaBajaInicio", fechaBajaInicio) :
                new ObjectParameter("FechaBajaInicio", typeof(string));
    
            var fechaBajaFinParameter = fechaBajaFin != null ?
                new ObjectParameter("FechaBajaFin", fechaBajaFin) :
                new ObjectParameter("FechaBajaFin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComFindTopics_Result>("ComFindTopics", nomtemaParameter, idCuentaParameter, idCategoriaParameter, fechaCreacionInicioParameter, fechaCreacionFinParameter, vigtemaParameter, fechaBajaInicioParameter, fechaBajaFinParameter);
        }
    
        public virtual ObjectResult<ComLessonLearnedActivity_Result> ComLessonLearnedActivity(Nullable<int> idLeccionAprendida, Nullable<int> idCuenta)
        {
            var idLeccionAprendidaParameter = idLeccionAprendida.HasValue ?
                new ObjectParameter("idLeccionAprendida", idLeccionAprendida) :
                new ObjectParameter("idLeccionAprendida", typeof(int));
    
            var idCuentaParameter = idCuenta.HasValue ?
                new ObjectParameter("idCuenta", idCuenta) :
                new ObjectParameter("idCuenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComLessonLearnedActivity_Result>("ComLessonLearnedActivity", idLeccionAprendidaParameter, idCuentaParameter);
        }
    
        public virtual ObjectResult<ComListLessonsLearnedTickets_Result> ComListLessonsLearnedTickets(Nullable<int> idTicket, Nullable<int> consulta)
        {
            var idTicketParameter = idTicket.HasValue ?
                new ObjectParameter("idTicket", idTicket) :
                new ObjectParameter("idTicket", typeof(int));
    
            var consultaParameter = consulta.HasValue ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComListLessonsLearnedTickets_Result>("ComListLessonsLearnedTickets", idTicketParameter, consultaParameter);
        }
    
        public virtual ObjectResult<ComSaveTheme_Result> ComSaveTheme(Nullable<int> idTema, Nullable<int> idCuenta, Nullable<int> idCuentaCatTema, Nullable<int> idCategoria, string nomtema, Nullable<bool> vigTema, string usuario, string dateStart, string dateEnd, Nullable<int> accoUser, string dateUpdate, string usuarioUpdate, Nullable<int> tipoOperacion)
        {
            var idTemaParameter = idTema.HasValue ?
                new ObjectParameter("IdTema", idTema) :
                new ObjectParameter("IdTema", typeof(int));
    
            var idCuentaParameter = idCuenta.HasValue ?
                new ObjectParameter("IdCuenta", idCuenta) :
                new ObjectParameter("IdCuenta", typeof(int));
    
            var idCuentaCatTemaParameter = idCuentaCatTema.HasValue ?
                new ObjectParameter("IdCuentaCatTema", idCuentaCatTema) :
                new ObjectParameter("IdCuentaCatTema", typeof(int));
    
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("IdCategoria", idCategoria) :
                new ObjectParameter("IdCategoria", typeof(int));
    
            var nomtemaParameter = nomtema != null ?
                new ObjectParameter("Nomtema", nomtema) :
                new ObjectParameter("Nomtema", typeof(string));
    
            var vigTemaParameter = vigTema.HasValue ?
                new ObjectParameter("VigTema", vigTema) :
                new ObjectParameter("VigTema", typeof(bool));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("DateStart", dateStart) :
                new ObjectParameter("DateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("DateEnd", dateEnd) :
                new ObjectParameter("DateEnd", typeof(string));
    
            var accoUserParameter = accoUser.HasValue ?
                new ObjectParameter("AccoUser", accoUser) :
                new ObjectParameter("AccoUser", typeof(int));
    
            var dateUpdateParameter = dateUpdate != null ?
                new ObjectParameter("DateUpdate", dateUpdate) :
                new ObjectParameter("DateUpdate", typeof(string));
    
            var usuarioUpdateParameter = usuarioUpdate != null ?
                new ObjectParameter("UsuarioUpdate", usuarioUpdate) :
                new ObjectParameter("UsuarioUpdate", typeof(string));
    
            var tipoOperacionParameter = tipoOperacion.HasValue ?
                new ObjectParameter("tipoOperacion", tipoOperacion) :
                new ObjectParameter("tipoOperacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComSaveTheme_Result>("ComSaveTheme", idTemaParameter, idCuentaParameter, idCuentaCatTemaParameter, idCategoriaParameter, nomtemaParameter, vigTemaParameter, usuarioParameter, dateStartParameter, dateEndParameter, accoUserParameter, dateUpdateParameter, usuarioUpdateParameter, tipoOperacionParameter);
        }
    
        public virtual ObjectResult<ComTrayLessonsLearned_Result> ComTrayLessonsLearned(Nullable<int> nivel1, Nullable<int> nivel2, Nullable<int> nivel3, Nullable<int> nivel4, Nullable<int> idTema, string fechaCreacionInicio_, string fechaCreacionFin_, Nullable<int> nroRevisiones, string palabraClave, string estadoAprobacion, Nullable<int> puntuacion, Nullable<int> tipoTicket)
        {
            var nivel1Parameter = nivel1.HasValue ?
                new ObjectParameter("nivel1", nivel1) :
                new ObjectParameter("nivel1", typeof(int));
    
            var nivel2Parameter = nivel2.HasValue ?
                new ObjectParameter("nivel2", nivel2) :
                new ObjectParameter("nivel2", typeof(int));
    
            var nivel3Parameter = nivel3.HasValue ?
                new ObjectParameter("nivel3", nivel3) :
                new ObjectParameter("nivel3", typeof(int));
    
            var nivel4Parameter = nivel4.HasValue ?
                new ObjectParameter("nivel4", nivel4) :
                new ObjectParameter("nivel4", typeof(int));
    
            var idTemaParameter = idTema.HasValue ?
                new ObjectParameter("idTema", idTema) :
                new ObjectParameter("idTema", typeof(int));
    
            var fechaCreacionInicio_Parameter = fechaCreacionInicio_ != null ?
                new ObjectParameter("fechaCreacionInicio_", fechaCreacionInicio_) :
                new ObjectParameter("fechaCreacionInicio_", typeof(string));
    
            var fechaCreacionFin_Parameter = fechaCreacionFin_ != null ?
                new ObjectParameter("fechaCreacionFin_", fechaCreacionFin_) :
                new ObjectParameter("fechaCreacionFin_", typeof(string));
    
            var nroRevisionesParameter = nroRevisiones.HasValue ?
                new ObjectParameter("nroRevisiones", nroRevisiones) :
                new ObjectParameter("nroRevisiones", typeof(int));
    
            var palabraClaveParameter = palabraClave != null ?
                new ObjectParameter("palabraClave", palabraClave) :
                new ObjectParameter("palabraClave", typeof(string));
    
            var estadoAprobacionParameter = estadoAprobacion != null ?
                new ObjectParameter("estadoAprobacion", estadoAprobacion) :
                new ObjectParameter("estadoAprobacion", typeof(string));
    
            var puntuacionParameter = puntuacion.HasValue ?
                new ObjectParameter("puntuacion", puntuacion) :
                new ObjectParameter("puntuacion", typeof(int));
    
            var tipoTicketParameter = tipoTicket.HasValue ?
                new ObjectParameter("tipoTicket", tipoTicket) :
                new ObjectParameter("tipoTicket", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComTrayLessonsLearned_Result>("ComTrayLessonsLearned", nivel1Parameter, nivel2Parameter, nivel3Parameter, nivel4Parameter, idTemaParameter, fechaCreacionInicio_Parameter, fechaCreacionFin_Parameter, nroRevisionesParameter, palabraClaveParameter, estadoAprobacionParameter, puntuacionParameter, tipoTicketParameter);
        }
    
        public virtual ObjectResult<ProcListarGestionDocumentos_Result> ProcListarGestionDocumentos(Nullable<int> idPersona, Nullable<int> idMarca, Nullable<int> tipoDocumento, string nombreDocumento, Nullable<int> sesionIdCuenta)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("idPersona", idPersona) :
                new ObjectParameter("idPersona", typeof(int));
    
            var idMarcaParameter = idMarca.HasValue ?
                new ObjectParameter("idMarca", idMarca) :
                new ObjectParameter("idMarca", typeof(int));
    
            var tipoDocumentoParameter = tipoDocumento.HasValue ?
                new ObjectParameter("tipoDocumento", tipoDocumento) :
                new ObjectParameter("tipoDocumento", typeof(int));
    
            var nombreDocumentoParameter = nombreDocumento != null ?
                new ObjectParameter("nombreDocumento", nombreDocumento) :
                new ObjectParameter("nombreDocumento", typeof(string));
    
            var sesionIdCuentaParameter = sesionIdCuenta.HasValue ?
                new ObjectParameter("sesionIdCuenta", sesionIdCuenta) :
                new ObjectParameter("sesionIdCuenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcListarGestionDocumentos_Result>("ProcListarGestionDocumentos", idPersonaParameter, idMarcaParameter, tipoDocumentoParameter, nombreDocumentoParameter, sesionIdCuentaParameter);
        }
    
        public virtual ObjectResult<ProcObtenerTipos_Result> ProcObtenerTipos(Nullable<int> idCuenta)
        {
            var idCuentaParameter = idCuenta.HasValue ?
                new ObjectParameter("idCuenta", idCuenta) :
                new ObjectParameter("idCuenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcObtenerTipos_Result>("ProcObtenerTipos", idCuentaParameter);
        }
    }
}
