//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electrodata.ERPElectrodata.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionDocumento
    {
        public GestionDocumento()
        {
            this.Adjuntoes = new HashSet<Adjunto>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<int> IdCompania { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<bool> Vigencia { get; set; }
        public Nullable<System.DateTime> FechaInicioVigencia { get; set; }
        public Nullable<System.DateTime> FechaFinVigencia { get; set; }
    
        public virtual ICollection<Adjunto> Adjuntoes { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
