//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electrodata.ERPElectrodata.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_DOCUMENT_ATTACH
    {
        public int ID_TYPE_DOCU_ATTA { get; set; }
        public string NAM_TYPE_DOCU_ATTA { get; set; }
        public Nullable<bool> VIG_TYPE_DOCU_ATTA { get; set; }
    }
}
