//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSENCE
    {
        public int ID_ABSE { get; set; }
        public string COD_ABSE { get; set; }
        public Nullable<System.DateTime> SIN_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public Nullable<System.DateTime> RET_DATE { get; set; }
        public Nullable<int> NUM_DAYS { get; set; }
        public string SUM { get; set; }
        public Nullable<int> ID_TYPE_ABSE { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> ID_VACA_STAT { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
    
        public virtual TYPE_ABSENCE TYPE_ABSENCE { get; set; }
    }
}
