//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accion
    {
        public Accion()
        {
            this.PerfilMenuAccion = new HashSet<PerfilMenuAccion>();
            this.UsuarioAccion = new HashSet<UsuarioAccion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual ICollection<PerfilMenuAccion> PerfilMenuAccion { get; set; }
        public virtual ICollection<UsuarioAccion> UsuarioAccion { get; set; }
    }
}
