//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_CLIENT
    {
        public int ID_ACCO_CLIE { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> ID_CLIE { get; set; }
        public Nullable<bool> VIG_ACCO_CLIE { get; set; }
        public Nullable<bool> DEF_ACCO { get; set; }
        public Nullable<bool> VIS_REQU { get; set; }
        public Nullable<bool> VIS_ASSI { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
