//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNTING_MONTH
    {
        public ACCOUNTING_MONTH()
        {
            this.TARGETs = new HashSet<TARGET>();
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
        }
    
        public int ID_ACCO_MONT { get; set; }
        public Nullable<int> ID_ACCO_YEAR { get; set; }
        public Nullable<int> ACCO_MONT { get; set; }
        public string NAM_ACCO_MONT { get; set; }
        public Nullable<bool> LAST { get; set; }
    
        public virtual ACCOUNTING_YEAR ACCOUNTING_YEAR { get; set; }
        public virtual ICollection<TARGET> TARGETs { get; set; }
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
    }
}
