//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_TYPE
    {
        public ACCOUNT_TYPE()
        {
            this.ACCOUNTs = new HashSet<ACCOUNT>();
        }
    
        public int ID_ACCO_TYPE { get; set; }
        public string NAM_ACCO_TYPE { get; set; }
        public string DES_ACCO_TYPE { get; set; }
        public Nullable<bool> VIG_ACCO_TYPE { get; set; }
    
        public virtual ICollection<ACCOUNT> ACCOUNTs { get; set; }
    }
}
