//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public ACCOUNT()
        {
            this.ComponenteStockCabeceras = new HashSet<ComponenteStockCabecera>();
            this.CHANGE_IMPACT = new HashSet<CHANGE_IMPACT>();
            this.CHANGE_PRIORITY = new HashSet<CHANGE_PRIORITY>();
            this.CHANGE_TYPE = new HashSet<CHANGE_TYPE>();
            this.CHANGE_TYPE_TASK = new HashSet<CHANGE_TYPE_TASK>();
            this.SubTipoComponentes = new HashSet<SubTipoComponente>();
            this.TicketAutomaticoes = new HashSet<TicketAutomatico>();
            this.TicketConfiguracions = new HashSet<TicketConfiguracion>();
            this.ComCuentaCategoryTemas = new HashSet<ComCuentaCategoryTema>();
            this.ACCOUNT_CATEGORY = new HashSet<ACCOUNT_CATEGORY>();
            this.ACCOUNT_CLIENT = new HashSet<ACCOUNT_CLIENT>();
            this.ACCOUNT_PARAMETER = new HashSet<ACCOUNT_PARAMETER>();
            this.DELIVERY_RECEPTION = new HashSet<DELIVERY_RECEPTION>();
            this.GRUPOPLANTILLAs = new HashSet<GRUPOPLANTILLA>();
            this.SITEs = new HashSet<SITE>();
            this.CHANGE_REQUEST = new HashSet<CHANGE_REQUEST>();
            this.CategoriaConTareas = new HashSet<CategoriaConTareas>();
        }
    
        public int ID_ACCO { get; set; }
        public string NAM_ACCO { get; set; }
        public string DES_ACCO { get; set; }
        public Nullable<int> STAF_ACCO { get; set; }
        public string SIT_ACCO { get; set; }
        public string ACR_ACCO { get; set; }
        public int ID_UBIG { get; set; }
        public Nullable<decimal> AGR_ACCO { get; set; }
        public Nullable<decimal> IND_AGR_ACCO { get; set; }
        public string MON_ACCO { get; set; }
        public string SIM_MONE_ACCO { get; set; }
        public Nullable<int> CAL_ACCO { get; set; }
        public string LAT_ACCO { get; set; }
        public string LON_ACCO { get; set; }
        public Nullable<System.DateTime> DATE_STAR { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public Nullable<bool> VIS_COMP { get; set; }
        public Nullable<bool> TIME_MANUAL { get; set; }
        public Nullable<int> ID_ACCO_TYPE { get; set; }
        public Nullable<bool> FlagMovil { get; set; }
        public string Logo1Movil { get; set; }
        public string Logo2Movil { get; set; }
    
        public virtual ICollection<ComponenteStockCabecera> ComponenteStockCabeceras { get; set; }
        public virtual ICollection<CHANGE_IMPACT> CHANGE_IMPACT { get; set; }
        public virtual ICollection<CHANGE_PRIORITY> CHANGE_PRIORITY { get; set; }
        public virtual ICollection<CHANGE_TYPE> CHANGE_TYPE { get; set; }
        public virtual ICollection<CHANGE_TYPE_TASK> CHANGE_TYPE_TASK { get; set; }
        public virtual ICollection<SubTipoComponente> SubTipoComponentes { get; set; }
        public virtual ICollection<TicketAutomatico> TicketAutomaticoes { get; set; }
        public virtual ICollection<TicketConfiguracion> TicketConfiguracions { get; set; }
        public virtual ICollection<ComCuentaCategoryTema> ComCuentaCategoryTemas { get; set; }
        public virtual ACCOUNT_TYPE ACCOUNT_TYPE { get; set; }
        public virtual ICollection<ACCOUNT_CATEGORY> ACCOUNT_CATEGORY { get; set; }
        public virtual ICollection<ACCOUNT_CLIENT> ACCOUNT_CLIENT { get; set; }
        public virtual ICollection<ACCOUNT_PARAMETER> ACCOUNT_PARAMETER { get; set; }
        public virtual ICollection<DELIVERY_RECEPTION> DELIVERY_RECEPTION { get; set; }
        public virtual ICollection<GRUPOPLANTILLA> GRUPOPLANTILLAs { get; set; }
        public virtual ICollection<SITE> SITEs { get; set; }
        public virtual ICollection<CHANGE_REQUEST> CHANGE_REQUEST { get; set; }
        public virtual ICollection<CategoriaConTareas> CategoriaConTareas { get; set; }
    }
}
