//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_QUEUE
    {
        public ACCOUNT_QUEUE()
        {
            this.Capacidads = new HashSet<Capacidad>();
        }
    
        public int ID_ACCO_QUEUE { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> ID_QUEU { get; set; }
        public Nullable<bool> VIG_ACCO_QUEU { get; set; }
        public string ROL_ACCO_QUEU { get; set; }
        public Nullable<int> ID_PERS_ENTI_CORD { get; set; }
        public string EMA_ACCO_QUEU { get; set; }
        public Nullable<bool> VIS_ALL_QUEU { get; set; }
        public Nullable<int> ORD_ACCO_QUEU { get; set; }
        public Nullable<int> ID_PERS_ENTI_ASSI_DEFA { get; set; }
        public Nullable<bool> IS_CLIE { get; set; }
        public string CorreosCCTicketResuelto { get; set; }
    
        public virtual ICollection<Capacidad> Capacidads { get; set; }
    }
}
