//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_TYPE_ASSET
    {
        public ACCOUNT_TYPE_ASSET()
        {
            this.Componentes = new HashSet<Componente>();
        }
    
        public int ID { get; set; }
        public int ID_TYPE_ASSE { get; set; }
        public int ID_ACCO { get; set; }
        public Nullable<int> MONTH_LIFE { get; set; }
    
        public virtual ICollection<Componente> Componentes { get; set; }
    }
}
