//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActaConstitucion
    {
        public ActaConstitucion()
        {
            this.ActaInteresados = new HashSet<ActaInteresados>();
            this.ActaRiesgos = new HashSet<ActaRiesgos>();
            this.ActaFacturacion = new HashSet<ActaFacturacion>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdDocuSale { get; set; }
        public Nullable<int> IdPM { get; set; }
        public Nullable<int> IdPMCliente { get; set; }
        public Nullable<System.DateTime> FechaActa { get; set; }
        public string Nombre { get; set; }
        public string Alcance { get; set; }
        public string Requisito { get; set; }
        public string Objetivo { get; set; }
        public string Finalidad { get; set; }
        public string Justificacion { get; set; }
        public string Exclusion { get; set; }
        public string Restriccion { get; set; }
        public string Supuesto { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<int> Finalizado { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<ActaInteresados> ActaInteresados { get; set; }
        public virtual ICollection<ActaRiesgos> ActaRiesgos { get; set; }
        public virtual ICollection<ActaFacturacion> ActaFacturacion { get; set; }
        public virtual DOCUMENT_SALE DOCUMENT_SALE { get; set; }
    }
}
