//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY_LOG
    {
        public int ID_ACTI_LOG { get; set; }
        public int ID_CLIE { get; set; }
        public int ID_TYPE_ACT { get; set; }
        public Nullable<int> ID_SUBTYPE_ACT { get; set; }
        public Nullable<int> COD_SUBTYPE_ACT { get; set; }
        public string NAM_SUBTYPE_ACT { get; set; }
        public Nullable<System.DateTime> DATE_INIC { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public string COMENTARIO { get; set; }
        public string EMAIL { get; set; }
        public int USERID { get; set; }
        public Nullable<System.DateTime> CREATE_ACT_LOG { get; set; }
        public Nullable<System.DateTime> MODIFIED_ACT_LOG { get; set; }
        public Nullable<bool> VIG_ACTI_LOG { get; set; }
        public string CONTACTO { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public string MOTIVO_EDIT { get; set; }
        public Nullable<int> ID_PERS_ENTI_EDIT { get; set; }
        public Nullable<bool> CLOSE_TICKET { get; set; }
        public Nullable<bool> SCHEDULE_TICKET { get; set; }
        public Nullable<bool> CLOSE_TICKET_OP { get; set; }
        public Nullable<int> TIEMPO_ACT { get; set; }
        public Nullable<int> DETAILS_TICKETS { get; set; }
        public Nullable<int> ID_TICKET_OP { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> IdEtapa { get; set; }
        public Nullable<int> IdActividad { get; set; }
        public Nullable<int> IdSubcategoria { get; set; }
        public Nullable<bool> ActividadRemota { get; set; }
    }
}
