//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjunto
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> IdGestionDocumento { get; set; }
        public string KeyAdjunto { get; set; }
        public Nullable<int> Estado_KeyAdjunto { get; set; }
        public string Nombre { get; set; }
        public string Extension { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<int> IdCompania { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
    
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual GestionDocumento GestionDocumento { get; set; }
    }
}
