//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivosActividade
    {
        public int Id { get; set; }
        public Nullable<int> IdDocuSale { get; set; }
        public Nullable<int> IdCronograma { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public Nullable<System.DateTime> FechaActaConformidad { get; set; }
        public string NombreArchivo { get; set; }
        public string Extension { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaReprogramada { get; set; }
        public string Motivo { get; set; }
    
        public virtual TYPE_DOCUMENT_ATTACH TYPE_DOCUMENT_ATTACH { get; set; }
        public virtual Cronograma Cronograma { get; set; }
        public virtual DOCUMENT_SALE DOCUMENT_SALE { get; set; }
    }
}
