//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA
    {
        public int ID_AREA { get; set; }
        public Nullable<int> ID_AREA_PARENT { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public string NOM_AREA { get; set; }
        public string COD_AREA { get; set; }
        public Nullable<int> NIV_AREA { get; set; }
        public Nullable<bool> VIG_AREA { get; set; }
        public Nullable<int> ID_ACCO_PERT { get; set; }
        public string ACRONYM { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<int> IdCompania { get; set; }
    }
}
