//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSET
    {
        public ASSET()
        {
            this.ActivoMantenimientoes = new HashSet<ActivoMantenimiento>();
            this.CLIENT_ASSET = new HashSet<CLIENT_ASSET>();
            this.CONFIGURATIONs = new HashSet<CONFIGURATION>();
            this.AplicacionMovilActivo = new HashSet<AplicacionMovilActivo>();
        }
    
        public int ID_ASSE { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public string COD_ASSE { get; set; }
        public string NAM_EQUI { get; set; }
        public Nullable<int> ID_TYPE_ASSE { get; set; }
        public Nullable<int> LOTE { get; set; }
        public Nullable<int> ID_BUY_MODE { get; set; }
        public string SER_NUMB { get; set; }
        public string SOLPED { get; set; }
        public Nullable<int> ID_TICK { get; set; }
        public string SUM_ASSE { get; set; }
        public Nullable<int> ID_MANU { get; set; }
        public Nullable<int> ID_COMM_MODE { get; set; }
        public Nullable<int> ID_MANU_MODE { get; set; }
        public Nullable<int> ID_COST_CENT { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<System.DateTime> CREATE_ASSE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> VIENE_DE { get; set; }
        public Nullable<System.DateTime> ACQ_DATE { get; set; }
        public Nullable<int> MONTH_LIFE { get; set; }
        public string MAC_ADRR { get; set; }
        public Nullable<int> ID_SYST_OPER_TYPE_ASSE { get; set; }
        public Nullable<System.DateTime> DAT_STAR_LEAS { get; set; }
        public Nullable<System.DateTime> DAT_END_LEAS { get; set; }
        public Nullable<System.DateTime> fechaFinGarantia { get; set; }
        public string Contrato { get; set; }
        public Nullable<int> IdContrato { get; set; }
        public string IpLocal { get; set; }
        public string IpPublica { get; set; }
        public Nullable<int> ValorActivo { get; set; }
        public Nullable<int> RiesgoIntrinseco { get; set; }
        public string NumeroFactura { get; set; }
        public string GuiaRemision { get; set; }
        public string Mac_Address { get; set; }
        public string MacAddressBluetooth { get; set; }
        public string OrdenCompra { get; set; }
        public string Grupo { get; set; }
        public string Arrendador { get; set; }
        public Nullable<System.DateTime> FechaFinContrato { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public Nullable<int> IdArrendador { get; set; }
        public Nullable<int> TipoUsuario { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string IdActivo { get; set; }
        public Nullable<int> IdTipoServidor { get; set; }
        public string ProcesadorRam1 { get; set; }
        public string ProcesadorRam2 { get; set; }
        public Nullable<int> CantidadHD { get; set; }
        public string CapacidadHD { get; set; }
        public Nullable<int> IdSubTipoActivo { get; set; }
        public Nullable<int> UMinera { get; set; }
        public Nullable<int> IdModalidad { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public Nullable<int> IdPlan { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<int> CapacidadDisco { get; set; }
        public Nullable<int> CapacidadRam { get; set; }
        public Nullable<int> TipoDisco { get; set; }
        public Nullable<bool> Antivirus { get; set; }
    
        public virtual ACCOUNT_PARAMETER ACCOUNT_PARAMETER { get; set; }
        public virtual ACCOUNT_PARAMETER ACCOUNT_PARAMETER1 { get; set; }
        public virtual ACCOUNT_PARAMETER ACCOUNT_PARAMETER2 { get; set; }
        public virtual ICollection<ActivoMantenimiento> ActivoMantenimientoes { get; set; }
        public virtual COMMERCIAL_MODEL COMMERCIAL_MODEL { get; set; }
        public virtual MANUFACTURER_MODEL MANUFACTURER_MODEL { get; set; }
        public virtual SYSTEM_OPER_TYPE_ASSE SYSTEM_OPER_TYPE_ASSE { get; set; }
        public virtual TYPE_ASSET TYPE_ASSET { get; set; }
        public virtual ICollection<CLIENT_ASSET> CLIENT_ASSET { get; set; }
        public virtual ICollection<CONFIGURATION> CONFIGURATIONs { get; set; }
        public virtual ICollection<AplicacionMovilActivo> AplicacionMovilActivo { get; set; }
        public virtual TICKET TICKET { get; set; }
    }
}
