//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AssistanceEntities : DbContext
    {
        public AssistanceEntities()
            : base("name=AssistanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ON_VERIFY> ON_VERIFY { get; set; }
        public virtual DbSet<TYPE_REGISTER> TYPE_REGISTER { get; set; }
        public virtual DbSet<VACATION_AND_ABSENCE> VACATION_AND_ABSENCE { get; set; }
    
        public virtual ObjectResult<TAL_ASSI_GRAP_Result> TAL_ASSI_GRAP(Nullable<int> iD_PERS_ENTI, Nullable<int> iD_YEAR, Nullable<int> iD_MONT)
        {
            var iD_PERS_ENTIParameter = iD_PERS_ENTI.HasValue ?
                new ObjectParameter("ID_PERS_ENTI", iD_PERS_ENTI) :
                new ObjectParameter("ID_PERS_ENTI", typeof(int));
    
            var iD_YEARParameter = iD_YEAR.HasValue ?
                new ObjectParameter("ID_YEAR", iD_YEAR) :
                new ObjectParameter("ID_YEAR", typeof(int));
    
            var iD_MONTParameter = iD_MONT.HasValue ?
                new ObjectParameter("ID_MONT", iD_MONT) :
                new ObjectParameter("ID_MONT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TAL_ASSI_GRAP_Result>("TAL_ASSI_GRAP", iD_PERS_ENTIParameter, iD_YEARParameter, iD_MONTParameter);
        }
    }
}
