//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACHED_PROJECT
    {
        public int ID_ATTA_PROJ { get; set; }
        public Nullable<int> ID_PROJ { get; set; }
        public string NAM_ATTA_PROJ { get; set; }
        public string EXT_ATTA_PROJ { get; set; }
        public Nullable<System.DateTime> CREATE_ATTA_PROJ { get; set; }
        public string KEY_ATTA_PROJ { get; set; }
        public Nullable<int> ID_TYPE_ATTA_PROJ { get; set; }
        public Nullable<bool> DELETE_ATTA_PROJ { get; set; }
    
        public virtual PROJECT PROJECT { get; set; }
        public virtual TYPE_ATTACH_PROJECT TYPE_ATTACH_PROJECT { get; set; }
    }
}
