//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACH_EVENT
    {
        public int ID_ATTA_EVEN { get; set; }
        public Nullable<int> ID_EVEN { get; set; }
        public string NAM_ATTA_EVEN { get; set; }
        public string EXT_ATTA_EVEN { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
