//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACHED_TICKET_FORMAT
    {
        public int ID_ATTA_TICK_FORM { get; set; }
        public string NAM_ATTA { get; set; }
        public string EXT_ATTA { get; set; }
        public Nullable<int> ID_TICK { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> ID_DETA_TICK { get; set; }
    }
}
