//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACHED
    {
        public int ID_ATTA { get; set; }
        public string NAM_ATTA { get; set; }
        public string EXT_ATTA { get; set; }
        public Nullable<int> ID_INCI { get; set; }
        public Nullable<int> ID_TRANSACTION { get; set; }
        public Nullable<int> ID_DETA_INCI { get; set; }
        public Nullable<int> ID_ASSE { get; set; }
        public Nullable<int> ID_CLIE_ASSE { get; set; }
        public Nullable<System.DateTime> CREATE_ATTA { get; set; }
        public Nullable<int> ID_ACTI_DOCU_SALE { get; set; }
        public Nullable<int> ID_DOCU_SALE { get; set; }
        public string KEY_ATTA { get; set; }
        public Nullable<int> ID_TYPE_DOCU_ATTA { get; set; }
        public Nullable<bool> DELETE_ATTA { get; set; }
        public Nullable<System.DateTime> FechaActaConformidad { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Indicador { get; set; }
        public Nullable<int> IdLeccionAprendida { get; set; }
        public Nullable<int> IdActivoMant { get; set; }
        public Nullable<int> ID_DOCU_EXPE { get; set; }
        public Nullable<int> ID_DETA_MOVI { get; set; }
        public Nullable<int> ID_SOLICITUD_PERSONAL { get; set; }
        public Nullable<int> ID_DELI_SUST { get; set; }
        public Nullable<int> ID_REQUE_EXPE { get; set; }
    
        public virtual DOCUMENT_EXPENSE DOCUMENT_EXPENSE { get; set; }
        public virtual DELIVERY_SUSTAIN DELIVERY_SUSTAIN { get; set; }
        public virtual DETAILS_TICKET DETAILS_TICKET { get; set; }
        public virtual TICKET TICKET { get; set; }
    }
}
