//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACHED_DELIVERY_RECEPTION
    {
        public int ID_ATTA_DELI_RECE { get; set; }
        public string NAM_ATTA_DELI_RECE { get; set; }
        public string EXT_ATTA_DELI_RECE { get; set; }
        public Nullable<int> ID_DELI_RECE { get; set; }
        public Nullable<System.DateTime> CREATE_ATTA_DELI_RECE { get; set; }
    
        public virtual DELIVERY_RECEPTION DELIVERY_RECEPTION { get; set; }
    }
}
