//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARY
    {
        public int ID_BENE { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_KINDRED { get; set; }
        public string LAS_NAME { get; set; }
        public string MOT_NAME { get; set; }
        public string FIR_NAME { get; set; }
        public string SEC_NAME { get; set; }
        public Nullable<System.DateTime> DATE_BRITH { get; set; }
        public string NUMB_DNI { get; set; }
        public Nullable<bool> ATT_DNI { get; set; }
        public Nullable<bool> ATT_EVID_STUD { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
    
        public virtual KINDRED KINDRED { get; set; }
        public virtual PERSON_ENTITY PERSON_ENTITY { get; set; }
    }
}
