//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUY_MODE
    {
        public int ID_BUY_MODE { get; set; }
        public string NAM_BUY_MODE { get; set; }
        public string DES_BUY_MODE { get; set; }
        public Nullable<bool> VIG_BUY_MODE { get; set; }
    }
}
