//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        public Candidato()
        {
            this.CaracteristicasCandidato = new HashSet<CaracteristicasCandidato>();
            this.Referencia = new HashSet<Referencia>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdEstadoCandidato { get; set; }
        public Nullable<int> IdSolicitudPersonal { get; set; }
        public Nullable<int> IdProfesion { get; set; }
        public string CurriculumVitae { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<int> PretencionSalarial { get; set; }
        public string Estudios { get; set; }
        public string Observacion { get; set; }
        public string ComentarioJefe { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public bool Estado { get; set; }
    
        public virtual EstadoCandidato EstadoCandidato { get; set; }
        public virtual ICollection<CaracteristicasCandidato> CaracteristicasCandidato { get; set; }
        public virtual ICollection<Referencia> Referencia { get; set; }
        public virtual SolicitudPersonal SolicitudPersonal { get; set; }
    }
}
