//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGO
    {
        public int ID_CARG { get; set; }
        public string NAM_CARG { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> ID_AREA { get; set; }
        public Nullable<bool> VIG_CARG { get; set; }
        public string NAM_JOB_DESC { get; set; }
        public Nullable<int> ID_CARG_PARE { get; set; }
        public Nullable<bool> TALENT { get; set; }
        public Nullable<bool> GET_REPORT { get; set; }
        public Nullable<bool> MANAGEMENT { get; set; }
    }
}
