//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public int id_Categoria { get; set; }
        public Nullable<int> id_TipoAtencion { get; set; }
        public string Categoria1 { get; set; }
        public Nullable<double> Supervision_estimado { get; set; }
        public Nullable<double> Supervision_real { get; set; }
        public Nullable<double> Infraestructura_estimado { get; set; }
        public Nullable<double> Infraestructura_real { get; set; }
        public Nullable<double> HelpDesk_estimado { get; set; }
        public Nullable<double> HelpDesk_real { get; set; }
        public Nullable<double> SoporteUser_estimado { get; set; }
        public Nullable<double> SoporteUser_real { get; set; }
        public Nullable<double> Arquitectura_estimado { get; set; }
        public Nullable<double> Arquitectura_real { get; set; }
        public Nullable<double> ServicioDBA_estimado { get; set; }
        public Nullable<double> ServicioDBA_real { get; set; }
        public Nullable<double> TotalHoras_estimado { get; set; }
        public Nullable<double> TotalHoras_real { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
