//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public CATEGORY()
        {
            this.ACCOUNT_CATEGORY = new HashSet<ACCOUNT_CATEGORY>();
            this.Tareas = new HashSet<Tarea>();
            this.ComCuentaCategoryTemas = new HashSet<ComCuentaCategoryTema>();
            this.TARGETs = new HashSet<TARGET>();
            this.DETAILS_TICKET = new HashSet<DETAILS_TICKET>();
            this.CategoriaConTareas = new HashSet<CategoriaConTareas>();
        }
    
        public int ID_CATE { get; set; }
        public string NAM_CATE { get; set; }
        public string ACR_CATE { get; set; }
        public string ABR_CATE { get; set; }
        public string DES_CATE { get; set; }
        public Nullable<bool> VIG_CATE { get; set; }
        public Nullable<bool> DEF_CATE { get; set; }
        public Nullable<int> ID_CATE_PARE { get; set; }
        public Nullable<int> NIV_CATE { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public Nullable<int> ACCO_USR { get; set; }
        public Nullable<int> ID_TYPE_TICK { get; set; }
        public Nullable<int> IdTipoGestionCambio { get; set; }
        public Nullable<bool> AplicaTicketProblema { get; set; }
        public Nullable<bool> AplicaGestionActivos { get; set; }
        public Nullable<bool> FlagModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> IdSLADet { get; set; }
        public Nullable<bool> TieneTarea { get; set; }
        public Nullable<bool> AplicaNotificacion { get; set; }
        public Nullable<int> NivelSla { get; set; }
    
        public virtual ICollection<ACCOUNT_CATEGORY> ACCOUNT_CATEGORY { get; set; }
        public virtual CHANGE_TYPE CHANGE_TYPE { get; set; }
        public virtual ICollection<Tarea> Tareas { get; set; }
        public virtual ICollection<ComCuentaCategoryTema> ComCuentaCategoryTemas { get; set; }
        public virtual ICollection<TARGET> TARGETs { get; set; }
        public virtual ICollection<DETAILS_TICKET> DETAILS_TICKET { get; set; }
        public virtual ICollection<CategoriaConTareas> CategoriaConTareas { get; set; }
    }
}
