//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaConTareas
    {
        public CategoriaConTareas()
        {
            this.Tarea = new HashSet<Tarea>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdCate { get; set; }
        public Nullable<int> IdAcco { get; set; }
        public Nullable<bool> ResuelveTicket { get; set; }
        public Nullable<int> GrupoCate { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ICollection<Tarea> Tarea { get; set; }
    }
}
