//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaPreguntaEncuesta
    {
        public CategoriaPreguntaEncuesta()
        {
            this.PreguntaEncuesta = new HashSet<PreguntaEncuesta>();
        }
    
        public int IdCategoria { get; set; }
        public string NombreCategoria { get; set; }
        public bool EstadoCategoria { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public Nullable<int> UsuarioRegistra { get; set; }
        public int UsuarioActualizacion { get; set; }
    
        public virtual ICollection<PreguntaEncuesta> PreguntaEncuesta { get; set; }
    }
}
