//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANGE_TYPE_DETAIL
    {
        public int id { get; set; }
        public string detail { get; set; }
        public Nullable<int> idChangeType { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual CHANGE_TYPE CHANGE_TYPE { get; set; }
    }
}
