//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANGE_TYPE
    {
        public CHANGE_TYPE()
        {
            this.CHANGE_TYPE_DETAIL = new HashSet<CHANGE_TYPE_DETAIL>();
            this.CHANGE_REQUEST = new HashSet<CHANGE_REQUEST>();
            this.CATEGORies = new HashSet<CATEGORY>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string details { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> descripcion { get; set; }
        public Nullable<int> IdCuenta { get; set; }
    
        public virtual ICollection<CHANGE_TYPE_DETAIL> CHANGE_TYPE_DETAIL { get; set; }
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ICollection<CHANGE_REQUEST> CHANGE_REQUEST { get; set; }
        public virtual ICollection<CATEGORY> CATEGORies { get; set; }
    }
}
