//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANGE_APPROVED
    {
        public CHANGE_APPROVED()
        {
            this.CHANGE_DETAIL_PLAN_ATTACH = new HashSet<CHANGE_DETAIL_PLAN_ATTACH>();
        }
    
        public int id { get; set; }
        public Nullable<int> idChangeRequest { get; set; }
        public Nullable<int> idTypeRequest { get; set; }
        public int approver { get; set; }
        public Nullable<int> approvedby { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string justificationChange { get; set; }
        public Nullable<bool> activeJustified { get; set; }
        public Nullable<System.DateTime> changeDate { get; set; }
        public Nullable<System.DateTime> dateActiveJustified { get; set; }
        public Nullable<int> activeToplan { get; set; }
        public Nullable<System.DateTime> dateActiveToplan { get; set; }
        public Nullable<bool> VisNoti { get; set; }
    
        public virtual ICollection<CHANGE_DETAIL_PLAN_ATTACH> CHANGE_DETAIL_PLAN_ATTACH { get; set; }
        public virtual CHANGE_TYPE_REQUEST CHANGE_TYPE_REQUEST { get; set; }
        public virtual CHANGE_REQUEST CHANGE_REQUEST { get; set; }
    }
}
