//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANGE_TYPE_TASK
    {
        public CHANGE_TYPE_TASK()
        {
            this.CHANGE_DETAIL = new HashSet<CHANGE_DETAIL>();
        }
    
        public int ID { get; set; }
        public string TYPE_TASK { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual ICollection<CHANGE_DETAIL> CHANGE_DETAIL { get; set; }
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
