//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANGE_REQUEST
    {
        public CHANGE_REQUEST()
        {
            this.CHANGE_APPROVED = new HashSet<CHANGE_APPROVED>();
            this.CHANGE_DETAIL = new HashSet<CHANGE_DETAIL>();
            this.CHANGE_REQUEST_COMMENT = new HashSet<CHANGE_REQUEST_COMMENT>();
        }
    
        public int id { get; set; }
        public Nullable<int> idChangeType { get; set; }
        public Nullable<int> idChangeTypeDetail { get; set; }
        public string isImpactCheck { get; set; }
        public string otherImpact { get; set; }
        public Nullable<int> idPriority { get; set; }
        public string urgentDetail { get; set; }
        public string otherChange { get; set; }
        public string question1 { get; set; }
        public string question2 { get; set; }
        public string question3 { get; set; }
        public string question4 { get; set; }
        public string question5 { get; set; }
        public string question6 { get; set; }
        public string question7 { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> ID_PERS_ENTI_Modified { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<int> IdTicket { get; set; }
        public Nullable<int> IdTicketReq { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> ID_PERS_ENTI_ASSI { get; set; }
        public Nullable<int> idGroup { get; set; }
        public Nullable<int> idAttentioSite { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ICollection<CHANGE_APPROVED> CHANGE_APPROVED { get; set; }
        public virtual ICollection<CHANGE_DETAIL> CHANGE_DETAIL { get; set; }
        public virtual CHANGE_PRIORITY CHANGE_PRIORITY { get; set; }
        public virtual QUEUE QUEUE { get; set; }
        public virtual CHANGE_TYPE CHANGE_TYPE { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual ICollection<CHANGE_REQUEST_COMMENT> CHANGE_REQUEST_COMMENT { get; set; }
        public virtual TICKET TICKET { get; set; }
    }
}
