//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANGE_TYPE_REQUEST
    {
        public CHANGE_TYPE_REQUEST()
        {
            this.CHANGE_APPROVED = new HashSet<CHANGE_APPROVED>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public Nullable<bool> estado { get; set; }
        public string Abreviatura { get; set; }
        public string Color { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual ICollection<CHANGE_APPROVED> CHANGE_APPROVED { get; set; }
    }
}
