//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHRISTMAN_BASKET
    {
        public int ID_CHRI_BASK { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> YEA_CHRI_BASK { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> DATE_STAR { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public Nullable<bool> VIG_CHRI_BASK { get; set; }
    }
}
