//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIA_EPS
    {
        public CIA_EPS()
        {
            this.DETAIL_SURVEY_EPS = new HashSet<DETAIL_SURVEY_EPS>();
        }
    
        public int ID_CIA_EPS { get; set; }
        public string NAM_CIA_EPS { get; set; }
    
        public virtual ICollection<DETAIL_SURVEY_EPS> DETAIL_SURVEY_EPS { get; set; }
    }
}
