//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigoSMS
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> Celular { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> InicioVigencia { get; set; }
        public Nullable<System.DateTime> FinVigencia { get; set; }
        public string UsuarioSolicita { get; set; }
        public Nullable<System.DateTime> FechaSolicita { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdTick { get; set; }
    
        public virtual TICKET TICKET { get; set; }
    }
}
