//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMERCIAL_MODEL
    {
        public COMMERCIAL_MODEL()
        {
            this.ASSETs = new HashSet<ASSET>();
            this.ModeloComerxGrupo = new HashSet<ModeloComerxGrupo>();
        }
    
        public int ID_COMM_MODE { get; set; }
        public Nullable<int> ID_MANU { get; set; }
        public string NAM_COMM_MODE { get; set; }
        public string DESC_COMM_MODE { get; set; }
        public Nullable<int> UserIdCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UserIdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual MANUFACTURER MANUFACTURER { get; set; }
        public virtual ICollection<ASSET> ASSETs { get; set; }
        public virtual ICollection<ModeloComerxGrupo> ModeloComerxGrupo { get; set; }
    }
}
