//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponenteStockCabecera
    {
        public ComponenteStockCabecera()
        {
            this.ComponenteStockDetalle = new HashSet<ComponenteStockDetalle>();
        }
    
        public int IdCompStockCab { get; set; }
        public Nullable<int> IdTipoActivo { get; set; }
        public Nullable<int> IdComponente { get; set; }
        public Nullable<int> IdSubTipoComponente { get; set; }
        public Nullable<int> IdAcco { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CantidadTotal { get; set; }
        public Nullable<int> CantidadEnUso { get; set; }
        public Nullable<int> CantidadDisponible { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Solped { get; set; }
        public Nullable<System.DateTime> FechaAdquisicion { get; set; }
        public Nullable<int> IdLocacion { get; set; }
        public Nullable<int> IdCond { get; set; }
    
        public virtual Componente Componente { get; set; }
        public virtual ICollection<ComponenteStockDetalle> ComponenteStockDetalle { get; set; }
        public virtual CONDITION CONDITION { get; set; }
        public virtual SubTipoComponente SubTipoComponente { get; set; }
        public virtual TYPE_ASSET TYPE_ASSET { get; set; }
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual LOCATION LOCATION { get; set; }
    }
}
