//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPLIANCE_BY_OBJECTIVES
    {
        public int ID_COMP_OBJE { get; set; }
        public Nullable<int> ID_OBJE_STAF { get; set; }
        public Nullable<int> ID_COMP_OBJE_PARE { get; set; }
        public Nullable<System.DateTime> CREATE_COMP_OBJE { get; set; }
        public string COM_COMP_OBJE { get; set; }
        public Nullable<decimal> VAL_COMP_OBJE { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_TYPE_COMP { get; set; }
    }
}
