//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComTicketProblema
    {
        public int Id { get; set; }
        public Nullable<int> IdTicketProblema { get; set; }
        public Nullable<int> idTicket { get; set; }
        public Nullable<int> IdCategoria1 { get; set; }
        public Nullable<int> IdCategoria2 { get; set; }
        public Nullable<int> IdCategoria3 { get; set; }
        public Nullable<int> IdCategoria4 { get; set; }
        public Nullable<int> IdPrioridad { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public Nullable<int> IdCuenta { get; set; }
    }
}
