//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concurso
    {
        public int Id { get; set; }
        public Nullable<int> Campo1 { get; set; }
        public Nullable<int> Campo2 { get; set; }
        public Nullable<int> Campo3 { get; set; }
        public Nullable<int> Campo4 { get; set; }
        public Nullable<int> Campo5 { get; set; }
        public string Campo6 { get; set; }
        public string Campo7 { get; set; }
        public string Campo8 { get; set; }
        public string Campo9 { get; set; }
        public string Campo10 { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
