//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURATION
    {
        public int ID_CONF { get; set; }
        public Nullable<int> ID_CONF_PARE { get; set; }
        public Nullable<int> ID_ASSE { get; set; }
        public Nullable<int> ID_PARA_CONF { get; set; }
        public string VAL_CONF { get; set; }
        public Nullable<int> NIV_CONF { get; set; }
        public Nullable<bool> VIG_CONF { get; set; }
    
        public virtual PARAMETER_CONFIGURATION PARAMETER_CONFIGURATION { get; set; }
        public virtual ASSET ASSET { get; set; }
    }
}
