//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Cese
    {
        public int Id_ControlCese { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> Id_ModAtencion { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_PERS_ENTI_END { get; set; }
        public string Correo_Pers_Enti_End { get; set; }
        public string Cel_Pers_Enti_End { get; set; }
        public Nullable<int> Id_AreaPersonal { get; set; }
        public Nullable<int> ID_LOCA_Pers_Enti_End { get; set; }
        public Nullable<int> Id_Pers_Enti_Jefe { get; set; }
        public string Correo_JefeInmediato { get; set; }
        public string Cel_JefeInmediato { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public Nullable<int> Id_MotivoCese { get; set; }
        public Nullable<int> Id_TipoMotivoCese { get; set; }
        public Nullable<int> Id_ExamenMedico { get; set; }
        public Nullable<int> Id_Ampliacion_Exclusion { get; set; }
        public Nullable<int> Id_NivelRiesgo { get; set; }
        public Nullable<System.DateTime> FechaCese { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> ID_TICKET { get; set; }
        public string RUC_ACCO { get; set; }
        public Nullable<bool> SendMail { get; set; }
        public Nullable<System.DateTime> CreateMail { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
        public Nullable<int> ID_PERS_ENTI_EDIT { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Id_Area { get; set; }
        public Nullable<int> Id_Char { get; set; }
    }
}
