//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT_CONDITION
    {
        public CONTRACT_CONDITION()
        {
            this.PERSON_CONTRACT = new HashSet<PERSON_CONTRACT>();
        }
    
        public int ID_COND_CONT { get; set; }
        public string CONDITION { get; set; }
        public string DESC_COND { get; set; }
    
        public virtual ICollection<PERSON_CONTRACT> PERSON_CONTRACT { get; set; }
    }
}
