//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cronograma
    {
        public Cronograma()
        {
            this.ArchivosActividades = new HashSet<ArchivosActividade>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdDocuSale { get; set; }
        public string NombreActividad { get; set; }
        public Nullable<int> IdAccoPara { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> NroCronograma { get; set; }
        public Nullable<int> InicioCronograma { get; set; }
        public string Estilo { get; set; }
        public Nullable<int> Mile { get; set; }
        public Nullable<int> IdPersEnti { get; set; }
        public Nullable<int> Completo { get; set; }
        public Nullable<int> Grupo { get; set; }
        public Nullable<int> Padre { get; set; }
        public Nullable<int> Abierto { get; set; }
        public string Depende { get; set; }
        public string Subtitulo { get; set; }
        public string Notas { get; set; }
        public string Gantt { get; set; }
        public Nullable<int> Peso { get; set; }
        public Nullable<int> Recurso { get; set; }
        public Nullable<bool> AplicaHito { get; set; }
        public string Observaciones { get; set; }
        public string Entregables { get; set; }
    
        public virtual ACCOUNT_PARAMETER ACCOUNT_PARAMETER { get; set; }
        public virtual ICollection<ArchivosActividade> ArchivosActividades { get; set; }
        public virtual DOCUMENT_SALE DOCUMENT_SALE { get; set; }
    }
}
