//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosIngresadosActivo
    {
        public int ID { get; set; }
        public string Hostname { get; set; }
        public string Serie { get; set; }
        public string TipoActivo { get; set; }
        public string SubTipoActivo { get; set; }
        public string CodigoActivo { get; set; }
        public string Grupo { get; set; }
        public string Marca { get; set; }
        public string ModeloComercial { get; set; }
        public string ModeloFabrica { get; set; }
        public string Arrendedor { get; set; }
        public string Solped { get; set; }
        public string CentroCosto { get; set; }
        public string ModoCompra { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string FechaFinContrato { get; set; }
        public string Sitio { get; set; }
        public string Locacion { get; set; }
        public string FechaAdquisicion { get; set; }
        public string Comentarios { get; set; }
        public string Condicion { get; set; }
        public string Estado { get; set; }
        public string UsuarioResponsable { get; set; }
        public string UsuarioAsignado { get; set; }
        public string IpLocal { get; set; }
        public string IpPublica { get; set; }
        public string Contrato { get; set; }
        public string MacFisica { get; set; }
        public string MacInalambrica { get; set; }
        public string MacBluetooth { get; set; }
        public Nullable<bool> Valido { get; set; }
        public string Observacion { get; set; }
    }
}
