//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_SUSTAIN
    {
        public DELIVERY_SUSTAIN()
        {
            this.DELIVERY_SUSTAIN_ACTIVITY = new HashSet<DELIVERY_SUSTAIN_ACTIVITY>();
            this.REQUEST_EXPENSE = new HashSet<REQUEST_EXPENSE>();
            this.ATTACHEDs = new HashSet<ATTACHED>();
        }
    
        public int ID_DELI_SUST { get; set; }
        public Nullable<int> ID_PERS_ENTI_ASSI { get; set; }
        public Nullable<int> ID_PERS_ENTI_APPR { get; set; }
        public Nullable<int> ID_TYPE_DELI_SUST { get; set; }
        public string DOC_NUMB { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string NAM_ANEX { get; set; }
        public string COIN { get; set; }
        public Nullable<decimal> DOC_AMOU { get; set; }
        public Nullable<decimal> DOC_REMA { get; set; }
        public Nullable<decimal> AMO_AVAI { get; set; }
        public string COD_ANEX { get; set; }
        public string DOC_STAT { get; set; }
        public Nullable<System.DateTime> DAT_REGI { get; set; }
        public Nullable<decimal> TYP_CHAN { get; set; }
        public string NUM_ACCO { get; set; }
        public Nullable<int> ID_STAT_DELI_SUST { get; set; }
        public Nullable<decimal> AMO_PREV { get; set; }
        public Nullable<int> ID_PREV { get; set; }
        public Nullable<decimal> AMO_AVAI_PREV { get; set; }
        public Nullable<bool> AMO_AVAI_ASSI { get; set; }
        public string NUM_CHEC { get; set; }
        public string NumeroPRC { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public Nullable<System.DateTime> CREATED_MAIL { get; set; }
    
        public virtual ICollection<DELIVERY_SUSTAIN_ACTIVITY> DELIVERY_SUSTAIN_ACTIVITY { get; set; }
        public virtual ICollection<REQUEST_EXPENSE> REQUEST_EXPENSE { get; set; }
        public virtual TYPE_DELI_SUST TYPE_DELI_SUST { get; set; }
        public virtual ICollection<ATTACHED> ATTACHEDs { get; set; }
    }
}
