//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_SURVEY_EPS
    {
        public int ID_DETA_SURV_EPS { get; set; }
        public Nullable<int> ID_SURV_EPS { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_CIA_EPS { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
    
        public virtual CIA_EPS CIA_EPS { get; set; }
        public virtual SURVEY_EPS SURVEY_EPS { get; set; }
    }
}
