//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleTiempoSla
    {
        public int IdDetalleTiempoSLA { get; set; }
        public Nullable<int> IdTick { get; set; }
        public Nullable<int> IdDocuSale { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> TiempoReal { get; set; }
        public Nullable<int> IdSla { get; set; }
        public Nullable<int> IdPrioridad { get; set; }
        public Nullable<int> IdCategoriaSLA { get; set; }
    }
}
