//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILS_VACATION
    {
        public DETAILS_VACATION()
        {
            this.ATTACHED_VACATION = new HashSet<ATTACHED_VACATION>();
        }
    
        public int ID_DETA_VACA { get; set; }
        public Nullable<int> ID_VACA { get; set; }
        public Nullable<int> ID_TYPE_DETA_VACA { get; set; }
        public string COM_DETA_VACA { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DAT_REGI { get; set; }
    
        public virtual TYPE_DETAILS_VACATION TYPE_DETAILS_VACATION { get; set; }
        public virtual ICollection<ATTACHED_VACATION> ATTACHED_VACATION { get; set; }
        public virtual VACATION VACATION { get; set; }
    }
}
