//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILS_FEEDBACK
    {
        public int ID_DETA_FEED { get; set; }
        public int ID_FEED { get; set; }
        public int ID_QUES { get; set; }
        public int VAL_QUES { get; set; }
    
        public virtual FEEDBACK FEEDBACK { get; set; }
    }
}
