//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_MOBILITY
    {
        public int ID_DETA_MOVI { get; set; }
        public Nullable<int> ID_DOCU_EXPE { get; set; }
        public Nullable<System.DateTime> DAT_EXPE { get; set; }
        public string REASON { get; set; }
        public string DESTINATION { get; set; }
        public string OBSERVATION { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<System.DateTime> DAT_REGI { get; set; }
        public Nullable<System.DateTime> DAT_REQU_APPR { get; set; }
        public Nullable<System.DateTime> DAT_APPR { get; set; }
        public Nullable<System.DateTime> DAT_REMO { get; set; }
        public Nullable<int> ID_STAT_DETA_MOBI { get; set; }
    
        public virtual DOCUMENT_EXPENSE DOCUMENT_EXPENSE { get; set; }
    }
}
