//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_CONTROL_TYPE
    {
        public DOCUMENT_CONTROL_TYPE()
        {
            this.DOCUMENT_CONTROL_CREATION_TYPE = new HashSet<DOCUMENT_CONTROL_CREATION_TYPE>();
            this.DOCUMENT_CONTROL_SUB_TYPE = new HashSet<DOCUMENT_CONTROL_SUB_TYPE>();
            this.DOCUMENT_CONTROL = new HashSet<DOCUMENT_CONTROL>();
        }
    
        public int ID_DOCU_CONT_TYPE { get; set; }
        public string NAM_DOCU_CONT_TYPE { get; set; }
        public string DESC_DOCU_CONT_TYPE { get; set; }
        public Nullable<bool> HAVE_SUB_TYPE { get; set; }
        public Nullable<bool> HAVE_SIDIGE { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual ICollection<DOCUMENT_CONTROL_CREATION_TYPE> DOCUMENT_CONTROL_CREATION_TYPE { get; set; }
        public virtual ICollection<DOCUMENT_CONTROL_SUB_TYPE> DOCUMENT_CONTROL_SUB_TYPE { get; set; }
        public virtual ICollection<DOCUMENT_CONTROL> DOCUMENT_CONTROL { get; set; }
    }
}
