//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_CONTROL_ACTION
    {
        public DOCUMENT_CONTROL_ACTION()
        {
            this.DOCUMENT_CONTROL_WORK = new HashSet<DOCUMENT_CONTROL_WORK>();
        }
    
        public int ID_DOCU_CONT_ACTIV { get; set; }
        public string NAM_DOCU_CONT_ACTI { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public string COLOR { get; set; }
    
        public virtual ICollection<DOCUMENT_CONTROL_WORK> DOCUMENT_CONTROL_WORK { get; set; }
    }
}
