//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_CONTROL_STORE
    {
        public DOCUMENT_CONTROL_STORE()
        {
            this.DOCUMENT_CONTROL = new HashSet<DOCUMENT_CONTROL>();
        }
    
        public int ID_DOCU_CONT_STOR { get; set; }
        public string NAM_DOCU_CONT_STOR { get; set; }
        public Nullable<int> ORD_DOCU_CONT_STOR { get; set; }
        public string GLYPH { get; set; }
    
        public virtual ICollection<DOCUMENT_CONTROL> DOCUMENT_CONTROL { get; set; }
    }
}
