//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_CONTROL
    {
        public DOCUMENT_CONTROL()
        {
            this.DOCUMENT_CONTROL_DETAIL = new HashSet<DOCUMENT_CONTROL_DETAIL>();
        }
    
        public int ID_DOCU_CONT { get; set; }
        public Nullable<int> ID_DOCU_CONT_CREA { get; set; }
        public Nullable<int> ID_DOCU_CONT_TYPE { get; set; }
        public Nullable<int> ID_DOCU_CONT_SUB_TYPE { get; set; }
        public Nullable<int> ID_DOCU_CONT_STOR { get; set; }
        public Nullable<int> ID_CIA { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> ID_DOCU_CONT_CARR { get; set; }
        public string SER_DOCU { get; set; }
        public string NUM_DOCU { get; set; }
        public Nullable<int> ID_PERS_ENTI_REMI { get; set; }
        public string SUB_DOCU { get; set; }
        public Nullable<int> ID_DOCU_CONT_ACTI { get; set; }
        public Nullable<int> ID_DOCU_CONT_ROL { get; set; }
        public string DOC_SIDIGE { get; set; }
        public Nullable<System.DateTime> DATE_RECE { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public Nullable<System.DateTime> CREATED_MAIL { get; set; }
    
        public virtual ICollection<DOCUMENT_CONTROL_DETAIL> DOCUMENT_CONTROL_DETAIL { get; set; }
        public virtual DOCUMENT_CONTROL_CARRIER DOCUMENT_CONTROL_CARRIER { get; set; }
        public virtual DOCUMENT_CONTROL_CREATION DOCUMENT_CONTROL_CREATION { get; set; }
        public virtual DOCUMENT_CONTROL_ROL DOCUMENT_CONTROL_ROL { get; set; }
        public virtual DOCUMENT_CONTROL_STORE DOCUMENT_CONTROL_STORE { get; set; }
        public virtual DOCUMENT_CONTROL_TYPE DOCUMENT_CONTROL_TYPE { get; set; }
    }
}
