//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_CONTROL_ATTACHED
    {
        public int ID_DOCU_CONT_ATTA { get; set; }
        public string NAM_DOCU_CONT_ATTA { get; set; }
        public string EXT_DOCU_CONT_ATTA { get; set; }
        public Nullable<int> ID_DOCU_CONT { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<int> IdDocumentoVenta { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> IdDocumentoContrato { get; set; }
    }
}
