//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_CONTROL_SUB_TYPE
    {
        public int ID_DOCU_CONT_SUB_TYPE { get; set; }
        public Nullable<int> ID_DOCU_CONT_TYPE { get; set; }
        public string NAM_DOCU_CONT_SUB_TYPE { get; set; }
        public Nullable<bool> REQUIRE_OP { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual DOCUMENT_CONTROL_TYPE DOCUMENT_CONTROL_TYPE { get; set; }
    }
}
