//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_DESTINATION
    {
        public int ID_EMAI_DEST { get; set; }
        public Nullable<int> ID_TYPE_EMAI { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<bool> VIG_EMAI_DEST { get; set; }
    }
}
