//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaPortalUsuario
    {
        public int Id { get; set; }
        public Nullable<int> IdTicket { get; set; }
        public Nullable<int> IdDetalleTicket { get; set; }
        public Nullable<int> IdEstadoEncuesta { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public string Comentario { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
