//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equivalencia
    {
        public int id_Equivalencia { get; set; }
        public string Nombre { get; set; }
        public string Area { get; set; }
        public string correoEdata { get; set; }
        public string usuarioRed { get; set; }
        public string correoHudbay { get; set; }
        public Nullable<int> id_GpoAsignacion { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
