//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaCalificacionCompetencia
    {
        public int Id { get; set; }
        public Nullable<int> IdEvaluacion { get; set; }
        public Nullable<int> IdCompetencia { get; set; }
        public Nullable<int> IdResultadoEvaluado { get; set; }
        public string ObsResultadoEvaluado { get; set; }
        public Nullable<int> IdResultadoJefe { get; set; }
        public string ObsResultadoJefe { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual EvaCompetencias EvaCompetencias { get; set; }
        public virtual EvaEvaluacion EvaEvaluacion { get; set; }
    }
}
