//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaEvaluacion
    {
        public EvaEvaluacion()
        {
            this.EvaArchivos = new HashSet<EvaArchivo>();
            this.EvaCalificacionCompetencia = new HashSet<EvaCalificacionCompetencia>();
            this.EvaCalificacionObjetivo = new HashSet<EvaCalificacionObjetivo>();
            this.EvaPlanMejora = new HashSet<EvaPlanMejora>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdPeriodo { get; set; }
        public Nullable<int> IdNombreEvaluacion { get; set; }
        public Nullable<int> IdPersEnti { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> UsuarioEvaluado { get; set; }
        public Nullable<System.DateTime> FechaEvaluado { get; set; }
        public Nullable<int> UsuarioJefe { get; set; }
        public Nullable<System.DateTime> FechaJefe { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<bool> ConformeEvaluado { get; set; }
        public Nullable<System.DateTime> FechaConformeEvaluado { get; set; }
        public Nullable<int> IdObjetivo { get; set; }
        public Nullable<int> IdFeedBack { get; set; }
    
        public virtual PERSON_ENTITY PERSON_ENTITY { get; set; }
        public virtual ICollection<EvaArchivo> EvaArchivos { get; set; }
        public virtual ICollection<EvaCalificacionCompetencia> EvaCalificacionCompetencia { get; set; }
        public virtual ICollection<EvaCalificacionObjetivo> EvaCalificacionObjetivo { get; set; }
        public virtual EvaEstado EvaEstado { get; set; }
        public virtual EvaNombreEvaluacion EvaNombreEvaluacion { get; set; }
        public virtual EvaPeriodo EvaPeriodo { get; set; }
        public virtual ICollection<EvaPlanMejora> EvaPlanMejora { get; set; }
    }
}
