//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FREQUENCY_MONITORING
    {
        public FREQUENCY_MONITORING()
        {
            this.OBJETIVES = new HashSet<OBJETIVE>();
        }
    
        public int ID_FREQ_MONI { get; set; }
        public string NAM_FREQ_MONI { get; set; }
        public string DES_FREQ_MONI { get; set; }
    
        public virtual ICollection<OBJETIVE> OBJETIVES { get; set; }
    }
}
