//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestion_Usuarios
    {
        public int Id { get; set; }
        public Nullable<int> IdModAtencion { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public Nullable<int> IdAplicacion { get; set; }
        public Nullable<int> IdSolTrabajo { get; set; }
        public Nullable<int> IdUbigeo { get; set; }
        public Nullable<int> IdAreaPerso { get; set; }
        public Nullable<int> IdModContrato { get; set; }
        public Nullable<int> IdModTrabajo { get; set; }
        public Nullable<int> IdPersEnti_Reemp { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
        public Nullable<int> IdCandidate { get; set; }
        public Nullable<int> IdTicket { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual UBIGEO UBIGEO { get; set; }
    }
}
