//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPOPLANTILLA
    {
        public GRUPOPLANTILLA()
        {
            this.PLANTILLA = new HashSet<PLANTILLA>();
        }
    
        public int ID_GRUPO { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> USUARIOCREACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<int> USUARIOMODIFICA { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICA { get; set; }
        public Nullable<bool> ESTADO { get; set; }
    
        public virtual ICollection<PLANTILLA> PLANTILLA { get; set; }
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
