//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_SCHEDULER
    {
        public int ID_HIST_SCHE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE_HIST { get; set; }
        public Nullable<int> ID_SCHE { get; set; }
        public Nullable<System.DateTime> STA_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> ALL_DAY { get; set; }
        public string TIT_SCHE { get; set; }
        public Nullable<int> ID_REPE { get; set; }
        public Nullable<int> REP_EVER { get; set; }
        public Nullable<int> REP_ON { get; set; }
        public Nullable<int> ID_REPE_END { get; set; }
        public string REPE_END_VALU { get; set; }
        public Nullable<System.DateTime> END_SCHE { get; set; }
        public string DES_SCHE { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public Nullable<int> ID_USER_HIST { get; set; }
    
        public virtual SCHEDULER SCHEDULER { get; set; }
    }
}
