//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class report_hudbayEntities : DbContext
    {
        public report_hudbayEntities()
            : base("name=report_hudbayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Canal> Canal { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Equivalencia> Equivalencia { get; set; }
        public virtual DbSet<GpoAsignacion> GpoAsignacion { get; set; }
        public virtual DbSet<ServicesNow> ServicesNow { get; set; }
        public virtual DbSet<Solicitante> Solicitante { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TablaLookerStudio> TablaLookerStudio { get; set; }
        public virtual DbSet<TipoAtencion> TipoAtencion { get; set; }
        public virtual DbSet<SubCategoriaH> SubCategoriaHs { get; set; }
    }
}
