//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeEvidenciaEnvio
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdTipoEvidencia { get; set; }
        public Nullable<int> IdInformeDetalle { get; set; }
        public Nullable<int> Creador { get; set; }
        public Nullable<int> Actualizador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> EstadoEvidencia { get; set; }
    
        public virtual InformeEDDetalle InformeEDDetalle { get; set; }
    }
}
