//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformePlantillaGrafico
    {
        public int Id { get; set; }
        public Nullable<int> IdPlantilla { get; set; }
        public Nullable<int> IdCategoriaGraficos { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual InformePlantilla InformePlantilla { get; set; }
        public virtual InformeCategoriaGrafico InformeCategoriaGrafico { get; set; }
    }
}
