//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeCategoria
    {
        public InformeCategoria()
        {
            this.InformePlantillaCategorias = new HashSet<InformePlantillaCategoria>();
            this.InformeCategoriaGraficos = new HashSet<InformeCategoriaGrafico>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<bool> Expandible { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<InformePlantillaCategoria> InformePlantillaCategorias { get; set; }
        public virtual ICollection<InformeCategoriaGrafico> InformeCategoriaGraficos { get; set; }
    }
}
