//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeCategoriaGrafico
    {
        public InformeCategoriaGrafico()
        {
            this.InformePlantillaGraficos = new HashSet<InformePlantillaGrafico>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdGrafico { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual InformeCategoria InformeCategoria { get; set; }
        public virtual InformeGrafico InformeGrafico { get; set; }
        public virtual ICollection<InformePlantillaGrafico> InformePlantillaGraficos { get; set; }
    }
}
