//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeED
    {
        public InformeED()
        {
            this.InformeEDDetalle = new HashSet<InformeEDDetalle>();
            this.InformeImagenes = new HashSet<InformeImagenes>();
            this.MarcasdeInforme = new HashSet<MarcasdeInforme>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdDocuSale { get; set; }
        public Nullable<int> IdManu { get; set; }
        public Nullable<int> NroInformes { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public string Frecuencia { get; set; }
        public Nullable<int> Tiempo { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdTipoInforme { get; set; }
        public string DestinatarioCorreo { get; set; }
        public string DestinatarioenvioFisico { get; set; }
        public string DestinatarioenvioMesaPartes { get; set; }
        public Nullable<int> Diasmaximoenvio { get; set; }
        public string FrecuenciaPersonalizada { get; set; }
        public string TipoDiasEnvio { get; set; }
        public Nullable<int> TiempoFrecuenciaPersonalizada { get; set; }
        public string MostrarDiasRestantes { get; set; }
        public Nullable<int> DiasRangoIncompleto { get; set; }
    
        public virtual MANUFACTURER MANUFACTURER { get; set; }
        public virtual ICollection<InformeEDDetalle> InformeEDDetalle { get; set; }
        public virtual DOCUMENT_SALE DOCUMENT_SALE { get; set; }
        public virtual ICollection<InformeImagenes> InformeImagenes { get; set; }
        public virtual ICollection<MarcasdeInforme> MarcasdeInforme { get; set; }
    }
}
