//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeHistorial
    {
        public int Id { get; set; }
        public Nullable<int> IdInformeDetalle { get; set; }
        public Nullable<int> IdEstadoAnterior { get; set; }
        public Nullable<int> IdEstadoHistorial { get; set; }
        public Nullable<int> IdPersEnti { get; set; }
        public Nullable<System.DateTime> FechaHistorial { get; set; }
    
        public virtual InformeEDDetalle InformeEDDetalle { get; set; }
        public virtual EstadoHistorial EstadoHistorial { get; set; }
        public virtual EstadoInforme EstadoInforme { get; set; }
    }
}
