//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeComentarios
    {
        public InformeComentarios()
        {
            this.TicketPeriodoInforme = new HashSet<TicketPeriodoInforme>();
        }
    
        public int Id { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Creador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdInformeDetalle { get; set; }
        public string IdTick { get; set; }
        public Nullable<int> TipoCorreccion { get; set; }
        public Nullable<int> Vigencia { get; set; }
    
        public virtual InformeEDDetalle InformeEDDetalle { get; set; }
        public virtual ICollection<TicketPeriodoInforme> TicketPeriodoInforme { get; set; }
    }
}
