//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNOWLEDGE
    {
        public int ID_KNOW { get; set; }
        public Nullable<int> ID_AREA { get; set; }
        public Nullable<int> ID_KNOW_CATE { get; set; }
        public string NAM_KNOW { get; set; }
        public string DESC_KNOW { get; set; }
        public string NAM_ATTA { get; set; }
        public string EXT_ATTA { get; set; }
        public Nullable<System.DateTime> DATE_ATTA { get; set; }
        public Nullable<System.DateTime> CREATED_KNOW { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> VIG_KNOW { get; set; }
        public Nullable<int> ID_ENTI_CIA { get; set; }
        public Nullable<int> ID_ACCO_MONT { get; set; }
        public Nullable<int> ID_DOCU_SALE { get; set; }
    }
}
