//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNOWLEDGE_CATEGORY
    {
        public int ID_KNOW_CATE { get; set; }
        public string NAM_CATE { get; set; }
        public string DESC_CATE { get; set; }
        public Nullable<bool> VIG_CATE { get; set; }
        public Nullable<bool> KEEP_NAME { get; set; }
        public Nullable<int> ID_KNOW_CATE_PARE { get; set; }
        public Nullable<bool> REG_DATE_ATTA { get; set; }
        public Nullable<bool> ANY_DOWN { get; set; }
        public Nullable<bool> REG_FOLD { get; set; }
        public string ROL_ACCE { get; set; }
        public Nullable<bool> ALL_AREA { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
    }
}
