//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNOWLEDGE_TEMPLATE
    {
        public int ID_KNOW_TEMP { get; set; }
        public string NAM_TEMP { get; set; }
        public string EXT_FILE { get; set; }
    }
}
