//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTransaccione
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Tabla { get; set; }
        public string IdRegistro { get; set; }
        public string Campo { get; set; }
        public string ValorOriginal { get; set; }
        public string ValorNuevo { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
