//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANAGEMENT_COMMITTEE
    {
        public MANAGEMENT_COMMITTEE()
        {
            this.TARGETs = new HashSet<TARGET>();
        }
    
        public int ID_MANA_COMM { get; set; }
        public string NAM_MANA_COMM { get; set; }
    
        public virtual ICollection<TARGET> TARGETs { get; set; }
    }
}
