//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANUFACTURER
    {
        public MANUFACTURER()
        {
            this.MANUFACTURER_MODEL = new HashSet<MANUFACTURER_MODEL>();
            this.SALES_OPPORTUNITY = new HashSet<SALES_OPPORTUNITY>();
            this.SoporteFabricantes = new HashSet<SoporteFabricante>();
            this.SoporteEDs = new HashSet<SoporteED>();
            this.COMMERCIAL_MODEL = new HashSet<COMMERCIAL_MODEL>();
            this.InformeED = new HashSet<InformeED>();
            this.MarcaxGrupo = new HashSet<MarcaxGrupo>();
            this.MarcasdeInforme = new HashSet<MarcasdeInforme>();
        }
    
        public int ID_MANU { get; set; }
        public string NAM_MANU { get; set; }
        public string DESC_MANU { get; set; }
        public Nullable<int> UserIdModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UserIdCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual ICollection<MANUFACTURER_MODEL> MANUFACTURER_MODEL { get; set; }
        public virtual ICollection<SALES_OPPORTUNITY> SALES_OPPORTUNITY { get; set; }
        public virtual ICollection<SoporteFabricante> SoporteFabricantes { get; set; }
        public virtual ICollection<SoporteED> SoporteEDs { get; set; }
        public virtual ICollection<COMMERCIAL_MODEL> COMMERCIAL_MODEL { get; set; }
        public virtual ICollection<InformeED> InformeED { get; set; }
        public virtual ICollection<MarcaxGrupo> MarcaxGrupo { get; set; }
        public virtual ICollection<MarcasdeInforme> MarcasdeInforme { get; set; }
    }
}
