//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAME_CHART
    {
        public NAME_CHART()
        {
            this.CHARTs = new HashSet<CHART>();
        }
    
        public int ID_NAM_CHAR { get; set; }
        public string NAM_CHAR { get; set; }
        public Nullable<bool> VIG_CHAR { get; set; }
        public Nullable<int> ID_TYPE_CHAR { get; set; }
        public Nullable<bool> MANAGEMENT { get; set; }
        public string ICON { get; set; }
        public string NAM_CHAR_ENGL { get; set; }
        public string NAM_CHAR_SPAN { get; set; }
        public Nullable<bool> EDIT { get; set; }
        public string COD_NAM_CHAR { get; set; }
    
        public virtual TYPE_CHART TYPE_CHART { get; set; }
        public virtual ICollection<CHART> CHARTs { get; set; }
    }
}
