//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    
    public partial class NotificacionesResponsableCambio
    {
        public int IdTipo { get; set; }
        public int IdTipoMensaje { get; set; }
        public int IdAprobDet { get; set; }
        public int IdChangeRequest { get; set; }
        public string Notificacion { get; set; }
    }
}
