//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETIVE_INDICATOR
    {
        public OBJETIVE_INDICATOR()
        {
            this.OBJECT_BY_STAFF_INDICATOR = new HashSet<OBJECT_BY_STAFF_INDICATOR>();
        }
    
        public int ID_OBJE_INDI { get; set; }
        public Nullable<int> ID_OBJE { get; set; }
        public string NAM_OBJE_INDI { get; set; }
    
        public virtual ICollection<OBJECT_BY_STAFF_INDICATOR> OBJECT_BY_STAFF_INDICATOR { get; set; }
        public virtual OBJETIVE OBJETIVE { get; set; }
    }
}
