//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETIVE
    {
        public OBJETIVE()
        {
            this.OBJETIVES_PERSON = new HashSet<OBJETIVES_PERSON>();
            this.OBJECT_BY_STAFF = new HashSet<OBJECT_BY_STAFF>();
            this.OBJETIVE_INDICATOR = new HashSet<OBJETIVE_INDICATOR>();
            this.OBJETIVE_SCALE = new HashSet<OBJETIVE_SCALE>();
        }
    
        public int ID_OBJE { get; set; }
        public Nullable<int> ID_EVAL { get; set; }
        public string NAM_OBJE { get; set; }
        public string DES_OBJE { get; set; }
        public Nullable<int> ID_TYPE_OBJE { get; set; }
        public string MEASURED { get; set; }
        public Nullable<System.DateTime> APP_WHEN { get; set; }
        public Nullable<int> ID_STAT_OBJE { get; set; }
        public Nullable<int> ID_FREQ_MONI { get; set; }
        public Nullable<int> TOT_OBJE { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<int> ID_MEAS { get; set; }
    
        public virtual EVALUATION EVALUATION { get; set; }
        public virtual FREQUENCY_MONITORING FREQUENCY_MONITORING { get; set; }
        public virtual STATUS_OBJETIVES STATUS_OBJETIVES { get; set; }
        public virtual ICollection<OBJETIVES_PERSON> OBJETIVES_PERSON { get; set; }
        public virtual TYPE_OBJECTIVE TYPE_OBJECTIVE { get; set; }
        public virtual ICollection<OBJECT_BY_STAFF> OBJECT_BY_STAFF { get; set; }
        public virtual ICollection<OBJETIVE_INDICATOR> OBJETIVE_INDICATOR { get; set; }
        public virtual ICollection<OBJETIVE_SCALE> OBJETIVE_SCALE { get; set; }
    }
}
