//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECT_BY_STAFF_INDICATOR
    {
        public int ID_OBJE_STAF_INDI { get; set; }
        public Nullable<int> ID_OBJE_STAF { get; set; }
        public Nullable<int> ID_OBJE_INDI { get; set; }
        public string VAL_OBJE_STAF_INDI { get; set; }
    
        public virtual OBJECT_BY_STAFF OBJECT_BY_STAFF { get; set; }
        public virtual OBJETIVE_INDICATOR OBJETIVE_INDICATOR { get; set; }
    }
}
