//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objetivo
    {
        public Objetivo()
        {
            this.ObjetivoDetalle = new HashSet<ObjetivoDetalle>();
        }
    
        public int IdObjetivo { get; set; }
        public Nullable<int> id_pers_enti { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
        public Nullable<int> id_pers_enti_evalu { get; set; }
        public Nullable<int> IdPeriodo { get; set; }
        public Nullable<int> IdEstadoObjetivo { get; set; }
        public Nullable<int> NivelCumplimientoPonderado { get; set; }
        public Nullable<int> IdDesempeño { get; set; }
    
        public virtual EvaEscalaDesempeño EvaEscalaDesempeño { get; set; }
        public virtual EvaPeriodo EvaPeriodo { get; set; }
        public virtual ICollection<ObjetivoDetalle> ObjetivoDetalle { get; set; }
    }
}
