//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECT_BY_STAFF
    {
        public OBJECT_BY_STAFF()
        {
            this.OBJECT_BY_STAFF_INDICATOR = new HashSet<OBJECT_BY_STAFF_INDICATOR>();
        }
    
        public int ID_OBJE_STAF { get; set; }
        public Nullable<int> ID_EVAL_STAF { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_OBJE { get; set; }
        public string COD_OBJE_STAF { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> STA_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<int> ID_PERS_ENTI_ASSI { get; set; }
        public Nullable<decimal> VAL_OBJE_STATF { get; set; }
        public Nullable<int> ID_STAT_OBJE { get; set; }
        public Nullable<bool> VIG_OBJE_STAF { get; set; }
    
        public virtual EVALUATION_STAFF EVALUATION_STAFF { get; set; }
        public virtual OBJETIVE OBJETIVE { get; set; }
        public virtual ICollection<OBJECT_BY_STAFF_INDICATOR> OBJECT_BY_STAFF_INDICATOR { get; set; }
    }
}
