//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetivoDetalle
    {
        public int IdObjetivoDetalle { get; set; }
        public Nullable<int> IdObjetivo { get; set; }
        public Nullable<int> IdEstadoObjetivoDetalle { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
        public Nullable<int> OrdenIndicador { get; set; }
        public string Objetivo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> FormulaInvertida { get; set; }
        public Nullable<int> Ponderado { get; set; }
        public Nullable<int> IdUnidadMedida { get; set; }
        public Nullable<int> Meta { get; set; }
        public Nullable<int> ValorReal { get; set; }
        public Nullable<int> NivelCumplimiento { get; set; }
        public Nullable<int> NivelCumplimientoPonderado { get; set; }
    
        public virtual Objetivo Objetivo1 { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
