//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETIVES_PERSON
    {
        public int ID_OBJE_PERS { get; set; }
        public int ID_OBJE { get; set; }
        public int ID_PERS_ENTI { get; set; }
        public Nullable<bool> VIG_OBJE_PERS { get; set; }
    
        public virtual OBJETIVE OBJETIVE { get; set; }
        public virtual PERSON_ENTITY PERSON_ENTITY { get; set; }
    }
}
