//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETIVE_SCALE
    {
        public int ID_OBJE_SCAL { get; set; }
        public Nullable<int> ID_OBJE { get; set; }
        public Nullable<int> SCAL_INF { get; set; }
        public Nullable<int> SCAL_SUP { get; set; }
        public string COLOR { get; set; }
    
        public virtual OBJETIVE OBJETIVE { get; set; }
    }
}
