//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    
    public partial class ObtenerDatosInformeED_Result1
    {
        public Nullable<int> IdDocuSale { get; set; }
        public int IdInformeED { get; set; }
        public int IdMarca { get; set; }
        public string Marca { get; set; }
        public Nullable<int> NroInformes { get; set; }
        public string Frecuencia { get; set; }
        public int TiempoPersonalizado { get; set; }
        public string InicioSoporte { get; set; }
        public string FinSoporte { get; set; }
        public Nullable<int> Tiempo { get; set; }
        public int IdTipoInforme { get; set; }
        public string TipoInforme { get; set; }
        public string Observaciones { get; set; }
        public string destinoCorreo { get; set; }
        public string destinoFisico { get; set; }
        public string destinoMesapartes { get; set; }
        public string TipoPlazoEnvio { get; set; }
        public Nullable<int> DiasEnvio { get; set; }
        public Nullable<int> DiasRangoIncompleto { get; set; }
        public string MostrarRangosIncompletos { get; set; }
    }
}
