//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ON_VERIFY
    {
        public long ID_ON_FING { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
        public string NUM_TYPE_DI { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> ID_TYPE_REGI { get; set; }
        public string DES_ON_VERY { get; set; }
        public Nullable<System.DateTime> STA_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<int> ID_PERS_ENTY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> ID_DETE { get; set; }
        public Nullable<int> ID_CIA { get; set; }
        public Nullable<int> ID_HORA { get; set; }
    
        public virtual TYPE_REGISTER TYPE_REGISTER { get; set; }
    }
}
