//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTION_STATUS
    {
        public int ID_OPTI_STAT { get; set; }
        public Nullable<int> ID_PERS_STAT { get; set; }
        public Nullable<int> ID_PERS_STAT_OPTI { get; set; }
        public Nullable<int> VIG_OPTI { get; set; }
    }
}
