//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETER
    {
        public PARAMETER()
        {
            this.ACCOUNT_PARAMETER = new HashSet<ACCOUNT_PARAMETER>();
        }
    
        public int ID_PARA { get; set; }
        public string NAM_PARA { get; set; }
        public Nullable<bool> VIG_PARA { get; set; }
        public string DESC_PARA { get; set; }
    
        public virtual ICollection<ACCOUNT_PARAMETER> ACCOUNT_PARAMETER { get; set; }
    }
}
