//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_TYPE_ASSET
    {
        public int ID_PART_TYPE_ASSE { get; set; }
        public Nullable<int> ID_TYPE_ASSE { get; set; }
        public Nullable<int> ID_PARA_CONF { get; set; }
        public string NAM_PART_TYPE_ASSE { get; set; }
        public string DES_PART_TYPE_ASSE { get; set; }
        public Nullable<bool> VIS_PART_TYPE_ASSE { get; set; }
    
        public virtual PARAMETER_CONFIGURATION PARAMETER_CONFIGURATION { get; set; }
        public virtual TYPE_ASSET TYPE_ASSET { get; set; }
    }
}
