//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public Perfil()
        {
            this.UsuarioPerfils = new HashSet<UsuarioPerfil>();
            this.PerfilMenu = new HashSet<PerfilMenu>();
        }
    
        public int Id { get; set; }
        public string Perfil1 { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
    
        public virtual ICollection<UsuarioPerfil> UsuarioPerfils { get; set; }
        public virtual ICollection<PerfilMenu> PerfilMenu { get; set; }
    }
}
