//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilActivos
    {
        public int Id { get; set; }
        public Nullable<int> IdChar { get; set; }
        public Nullable<int> IdAccoPara { get; set; }
        public Nullable<int> IdTipoActivo { get; set; }
        public Nullable<int> IdPrograma { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
    
        public virtual ACCOUNT_PARAMETER ACCOUNT_PARAMETER { get; set; }
        public virtual Programa Programa { get; set; }
        public virtual TYPE_ASSET TYPE_ASSET { get; set; }
    }
}
