//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_STATUS_CHANGE
    {
        public int ID_PERS_STAT_CHAN { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_PERS_STAT { get; set; }
        public Nullable<int> ID_PERS_CONT { get; set; }
        public Nullable<System.DateTime> STAR_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ID_PERS_ENTI_TEMP { get; set; }
    }
}
