//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_INVOICE
    {
        public int ID_INVO { get; set; }
        public Nullable<int> ID_ACCO_MONT { get; set; }
        public int ID_PERS_ENTI { get; set; }
        public string NAM_ATTA { get; set; }
        public string EXT_ATTA { get; set; }
        public Nullable<System.DateTime> CREATE_ATTA { get; set; }
        public Nullable<bool> SIGNED { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ID_TYPE_PAYM { get; set; }
    
        public virtual PERSON_ENTITY PERSON_ENTITY { get; set; }
    }
}
