//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_DOCUMENTS
    {
        public int ID_PERS_DOCU { get; set; }
        public Nullable<int> ID_TYPE_DOCU { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public string NAM_ATTA { get; set; }
        public string EXT_ATTA { get; set; }
        public Nullable<System.DateTime> CREATE_ATTA { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ID_PERS_CONT { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<bool> Vigencia { get; set; }
        public Nullable<System.DateTime> FechaInicioVigencia { get; set; }
        public Nullable<System.DateTime> FechaFinVigencia { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdCertificacion { get; set; }
        public Nullable<int> IdInstitucion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ENVIO_NOTIFICACION { get; set; }
    
        public virtual Institucion Institucion { get; set; }
        public virtual PERSON_ENTITY PERSON_ENTITY { get; set; }
        public virtual TYPE_DOCUMENT TYPE_DOCUMENT { get; set; }
    }
}
