//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_PAYMENT
    {
        public int ID_PERS_PAYM { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_TYPE_PAYM { get; set; }
        public Nullable<int> ID_BANK { get; set; }
        public string NUM_ACCO { get; set; }
        public Nullable<System.DateTime> DAT_STAR { get; set; }
        public Nullable<System.DateTime> DAT_END { get; set; }
    }
}
