//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_STATUS
    {
        public int ID_PERS_STAT { get; set; }
        public string NAM_STAT { get; set; }
        public Nullable<bool> VIS_STAT { get; set; }
        public Nullable<int> ORD_PERS_STAT { get; set; }
    }
}
