//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_CONTRACT_CHART
    {
        public int ID_PERS_CONT { get; set; }
        public int ID_CHAR { get; set; }
        public Nullable<bool> VIG_CONT_CHAR { get; set; }
        public Nullable<bool> IS_CONTRACT { get; set; }
        public Nullable<System.DateTime> DAT_STAR { get; set; }
        public Nullable<System.DateTime> DAT_END { get; set; }
    }
}
