//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETTY_CASH_ASSIGNED
    {
        public int ID_PETT_CASH_ASSI { get; set; }
        public Nullable<int> ID_PERS_ENTI_ASSI { get; set; }
        public Nullable<int> ID_PERS_ENTI_APPR { get; set; }
        public Nullable<bool> VIG_PETT_CASH_ASSI { get; set; }
        public Nullable<bool> APP_ANY_REQU { get; set; }
        public Nullable<int> ID_PERS_ENTI_APPR_VIAT { get; set; }
    }
}
