//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantillaInforme
    {
        public PlantillaInforme()
        {
            this.PlantillaAdicionales = new HashSet<PlantillaAdicionales>();
        }
    
        public int Id { get; set; }
        public string TituloPlantilla { get; set; }
        public string TituloInforme { get; set; }
        public Nullable<int> Id_Docu_Sale { get; set; }
        public Nullable<int> Id_Logo { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<int> Creador { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> Actualizador { get; set; }
        public Nullable<int> Vigencia { get; set; }
        public Nullable<int> AdicionalResolucion { get; set; }
        public Nullable<int> AdicionalAtencion { get; set; }
        public Nullable<int> AdicionalTabla { get; set; }
        public Nullable<int> AdicionalTicketAlerta { get; set; }
    
        public virtual ICollection<PlantillaAdicionales> PlantillaAdicionales { get; set; }
    }
}
