//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantillaIndex
    {
        public int Id { get; set; }
        public Nullable<int> Id_Plantilla { get; set; }
        public string Categoria { get; set; }
        public string Orden { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> CheckSeccion { get; set; }
        public Nullable<int> Vigencia { get; set; }
    }
}
