//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTILLA
    {
        public int ID_PLAN { get; set; }
        public Nullable<int> ID_GRUPO { get; set; }
        public Nullable<int> ID_TIPO_PLAN { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> USUARIOCREACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<int> USUARIOMODIFICA { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICA { get; set; }
        public Nullable<bool> ESTADO { get; set; }
    
        public virtual GRUPOPLANTILLA GRUPOPLANTILLA { get; set; }
        public virtual TIPOPLANTILLA TIPOPLANTILLA { get; set; }
    }
}
