//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POINT
    {
        public int ID_POIN { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_TICK { get; set; }
        public Nullable<int> ID_DETA_TICK { get; set; }
        public Nullable<int> ID_POIN_ACTI { get; set; }
        public Nullable<int> VAL_POIN { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
