//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIORITY
    {
        public PRIORITY()
        {
            this.TICKETs = new HashSet<TICKET>();
        }
    
        public int ID_PRIO { get; set; }
        public string NAM_PRIO { get; set; }
        public string DES_PRIO { get; set; }
        public Nullable<int> HOU_PRIO { get; set; }
        public string COL_PRIO { get; set; }
        public string ICO_PRIO { get; set; }
    
        public virtual ICollection<TICKET> TICKETs { get; set; }
    }
}
