//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosProyecto
    {
        public int Id { get; set; }
        public Nullable<int> IdDocuSale { get; set; }
        public Nullable<int> IdSoporteFAB { get; set; }
        public string Codigo { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual DOCUMENT_SALE DOCUMENT_SALE { get; set; }
        public virtual SoporteFabricante SoporteFabricante { get; set; }
    }
}
