//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramaLicencia
    {
        public ProgramaLicencia()
        {
            this.LicenciaPorUsuario = new HashSet<LicenciaPorUsuario>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdPrograma { get; set; }
        public string Codigo { get; set; }
        public Nullable<System.DateTime> FechaActivacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdTipoLicencia { get; set; }
        public Nullable<int> NroAsientos { get; set; }
        public string OrdenCompra { get; set; }
        public string Llave { get; set; }
        public string VersionLic { get; set; }
        public string Serie { get; set; }
        public string CodigoProducto { get; set; }
        public string CodigoActivacion { get; set; }
        public string CodigoAdicional { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Vencido { get; set; }
        public Nullable<int> IdModoInstalacion { get; set; }
        public Nullable<bool> Habilitado { get; set; }
        public string Solped { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string TipoLicencia { get; set; }
        public Nullable<int> CentroCosto { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public string IdLicenciaPorUsuario { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string AreaSolicitante { get; set; }
    
        public virtual Programa Programa { get; set; }
        public virtual ICollection<LicenciaPorUsuario> LicenciaPorUsuario { get; set; }
    }
}
