//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVISION_VACATION
    {
        public PROVISION_VACATION()
        {
            this.VACATION = new HashSet<VACATION>();
        }
    
        public int ID_PROV_VACA { get; set; }
        public Nullable<int> ID_WORK_PERI { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_ACCO_YEAR { get; set; }
        public Nullable<int> USED { get; set; }
        public Nullable<int> PENDING { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<decimal> TOTAL_TODAY { get; set; }
    
        public virtual WORK_PERIOD WORK_PERIOD { get; set; }
        public virtual PERSON_ENTITY PERSON_ENTITY { get; set; }
        public virtual ICollection<VACATION> VACATION { get; set; }
    }
}
