//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectosEmailRenovacion
    {
        public ProyectosEmailRenovacion()
        {
            this.ProyectosEmailRenovacionDetalle = new HashSet<ProyectosEmailRenovacionDetalle>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdDocuSale { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<System.DateTime> Fecha65Dias { get; set; }
        public Nullable<System.DateTime> Fecha60Dias { get; set; }
        public Nullable<System.DateTime> Fecha30Dias { get; set; }
        public Nullable<bool> OPGobierno { get; set; }
    
        public virtual ICollection<ProyectosEmailRenovacionDetalle> ProyectosEmailRenovacionDetalle { get; set; }
    }
}
