//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_TICKET
    {
        public int ID_QUES_TICK { get; set; }
        public Nullable<int> ID_QUES { get; set; }
        public Nullable<int> ID_SURV_TICK { get; set; }
        public string VAL_QUES_TICK { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
    
        public virtual SURVEY_TICKET SURVEY_TICKET { get; set; }
    }
}
