//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEUE
    {
        public QUEUE()
        {
            this.Tarea = new HashSet<Tarea>();
            this.CHANGE_REQUEST = new HashSet<CHANGE_REQUEST>();
            this.TICKETs = new HashSet<TICKET>();
        }
    
        public int ID_QUEU { get; set; }
        public string NAM_QUEU { get; set; }
        public string NAM_QUEU_REPO { get; set; }
        public string DES_QUEU { get; set; }
        public Nullable<bool> VIG_QUEU { get; set; }
        public Nullable<bool> VIS_ALL_QUEU { get; set; }
        public Nullable<int> ID_STAT { get; set; }
        public Nullable<int> LEV_QUEU { get; set; }
        public Nullable<bool> VIS_ALL_CHAN { get; set; }
        public string EMA_QUEU { get; set; }
    
        public virtual STATUS STATUS { get; set; }
        public virtual ICollection<Tarea> Tarea { get; set; }
        public virtual ICollection<CHANGE_REQUEST> CHANGE_REQUEST { get; set; }
        public virtual ICollection<TICKET> TICKETs { get; set; }
    }
}
