//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecursosAdicionales
    {
        public int Id { get; set; }
        public Nullable<int> IdSolicitudPersonal { get; set; }
        public string Recurso { get; set; }
        public string Descripcion { get; set; }
        public string TipoRecurso { get; set; }
        public string TipoAcceso { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual SolicitudPersonal SolicitudPersonal { get; set; }
    }
}
