//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referencia
    {
        public int Id { get; set; }
        public Nullable<int> IdCandidato { get; set; }
        public string Empresa { get; set; }
        public string NombreApellidoEmpleador { get; set; }
        public string CargoEmpleador { get; set; }
        public string RelacionLaboral { get; set; }
        public string CargoCandidato { get; set; }
        public string TiempoTrabajadoCandidato { get; set; }
        public string MotivoRetiroCandidato { get; set; }
        public Nullable<bool> VolveriaContratar { get; set; }
        public string CompetenciaSignificativa { get; set; }
        public string CompetenciaFortalecer { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public bool Estado { get; set; }
    
        public virtual Candidato Candidato { get; set; }
    }
}
