//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosEncuesta
    {
        public int IdRegistro { get; set; }
        public Nullable<int> UsuarioRegistra { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public Nullable<int> IdRespuesta { get; set; }
        public string RespuestaEspecifica { get; set; }
        public System.DateTime FechaResgistro { get; set; }
        public bool EstadoRespuesta { get; set; }
    
        public virtual PreguntaEncuesta PreguntaEncuesta { get; set; }
        public virtual RespuestasEncuesta RespuestasEncuesta { get; set; }
    }
}
