//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPEAT
    {
        public REPEAT()
        {
            this.SCHEDULERs = new HashSet<SCHEDULER>();
        }
    
        public int ID_REPE { get; set; }
        public string NAM_REPE { get; set; }
        public Nullable<int> ORD_REPE { get; set; }
        public Nullable<bool> VIG_REPE { get; set; }
        public string NAM_KENDO { get; set; }
    
        public virtual ICollection<SCHEDULER> SCHEDULERs { get; set; }
    }
}
