//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reprogramacion
    {
        public int Id { get; set; }
        public Nullable<int> IdCertificado { get; set; }
        public string Motivo { get; set; }
        public Nullable<System.DateTime> FechaProgramada { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public bool Estado { get; set; }
    
        public virtual Certificado Certificado { get; set; }
    }
}
