//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_EXPENSE
    {
        public REQUEST_EXPENSE()
        {
            this.REQUEST_EXPENSE_ACTIVITY = new HashSet<REQUEST_EXPENSE_ACTIVITY>();
            this.REQUEST_VIATICAL = new HashSet<REQUEST_VIATICAL>();
            this.DOCUMENT_EXPENSE = new HashSet<DOCUMENT_EXPENSE>();
        }
    
        public int ID_REQU_EXPE { get; set; }
        public string COD_REQU_EXPE { get; set; }
        public Nullable<int> ID_ENTI { get; set; }
        public Nullable<int> ID_DELI_SUST { get; set; }
        public Nullable<int> ID_TYPE_DELI_SUST { get; set; }
        public Nullable<int> ID_PERS_ENTI_REQU { get; set; }
        public Nullable<int> ID_PERS_ENTI_APPR { get; set; }
        public Nullable<int> ID_TICK { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> AMO_TOTA_DOCU { get; set; }
        public string JUSTIFICATION { get; set; }
        public Nullable<System.DateTime> DAT_REGI { get; set; }
        public Nullable<int> ID_STAT_REQU_EXPE_STAR { get; set; }
        public Nullable<int> ID_STAT_REQU_EXPE { get; set; }
        public Nullable<int> ID_PERS_ENTI_ASSI { get; set; }
        public Nullable<int> ID_PERS_ENTI_APPR_VIAT { get; set; }
        public Nullable<int> NUM_DAYS { get; set; }
        public Nullable<System.DateTime> DAT_DEPA { get; set; }
        public string DESTINATION { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public Nullable<System.DateTime> CREATED_MAIL { get; set; }
        public Nullable<bool> SEND_MAIL_USUARIO_DEVUELVE { get; set; }
        public Nullable<System.DateTime> CREATED_MAIL_USUARIO_DEVUELVE { get; set; }
        public Nullable<bool> DocumentoObservardo { get; set; }
        public string Observacion { get; set; }
    
        public virtual DELIVERY_SUSTAIN DELIVERY_SUSTAIN { get; set; }
        public virtual ICollection<REQUEST_EXPENSE_ACTIVITY> REQUEST_EXPENSE_ACTIVITY { get; set; }
        public virtual STATUS_REQUEST_EXPENSE STATUS_REQUEST_EXPENSE { get; set; }
        public virtual ICollection<REQUEST_VIATICAL> REQUEST_VIATICAL { get; set; }
        public virtual ICollection<DOCUMENT_EXPENSE> DOCUMENT_EXPENSE { get; set; }
        public virtual TYPE_DELI_SUST TYPE_DELI_SUST { get; set; }
    }
}
