//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_EXPENSE_ACTIVITY
    {
        public int ID_REQU_EXPE_ACTI { get; set; }
        public int ID_REQU_EXPE { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ID_STAT_REQU_EXPE { get; set; }
        public Nullable<System.DateTime> DAT_STAR { get; set; }
        public string REASON_REJECT { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public Nullable<System.DateTime> CREATED_MAIL { get; set; }
    
        public virtual REQUEST_EXPENSE REQUEST_EXPENSE { get; set; }
    }
}
