//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_VIATICAL
    {
        public int ID_REQU_EXPE { get; set; }
        public int ID_TYPE_VIAT { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
    
        public virtual TYPE_VIATICAL TYPE_VIATICAL { get; set; }
        public virtual REQUEST_EXPENSE REQUEST_EXPENSE { get; set; }
    }
}
