//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestasEncuesta
    {
        public RespuestasEncuesta()
        {
            this.RegistrosEncuesta = new HashSet<RegistrosEncuesta>();
        }
    
        public int IdRespuesta { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public string Respuesta { get; set; }
        public bool FlagEspecificar { get; set; }
        public System.DateTime FechaResgistro { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public int UsuarioRegistra { get; set; }
        public int UsuarioActualizacion { get; set; }
        public bool EstadoRespuesta { get; set; }
    
        public virtual PreguntaEncuesta PreguntaEncuesta { get; set; }
        public virtual ICollection<RegistrosEncuesta> RegistrosEncuesta { get; set; }
    }
}
