//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_TEAM
    {
        public ROL_TEAM()
        {
            this.TEAMs = new HashSet<TEAM>();
        }
    
        public int ID_ROL_TEAM { get; set; }
        public string NAM_ROL_TEAM { get; set; }
        public string DES_ROL_TEAM { get; set; }
    
        public virtual ICollection<TEAM> TEAMs { get; set; }
    }
}
