//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public ROOM()
        {
            this.ROOM_SCHEDULER = new HashSet<ROOM_SCHEDULER>();
        }
    
        public int ID_ROOM { get; set; }
        public string NAM_ROOM { get; set; }
        public string DES_ROOM { get; set; }
        public Nullable<bool> VIG_ROOM { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
    
        public virtual ICollection<ROOM_SCHEDULER> ROOM_SCHEDULER { get; set; }
    }
}
