//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_OPPORTUNITY
    {
        public int ID_SALE_OPPO { get; set; }
        public string COD_SALE_OPPO { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TIT_SALE_OPPO { get; set; }
        public Nullable<int> ID_COMP { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<decimal> AMO_SALE_OPPO { get; set; }
        public Nullable<decimal> MAR_SALE_OPPO { get; set; }
        public Nullable<int> ID_STAT_SALE_OPPO { get; set; }
        public Nullable<int> ID_STAT_SALE_OPPO_END { get; set; }
        public Nullable<int> ID_MANU { get; set; }
        public Nullable<System.DateTime> CLO_DATE { get; set; }
        public string SUM_SALE_OPPO { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual STATUS_SALES_OPPORTUNITY STATUS_SALES_OPPORTUNITY { get; set; }
        public virtual STATUS_SALES_OPPORTUNITY STATUS_SALES_OPPORTUNITY1 { get; set; }
        public virtual MANUFACTURER MANUFACTURER { get; set; }
    }
}
