//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public int ID_SALE { get; set; }
        public string OP_SALE { get; set; }
        public Nullable<int> ID_COMP { get; set; }
        public string DET_SALE { get; set; }
        public string SUM_SALE { get; set; }
        public string UserId { get; set; }
    }
}
