//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULER
    {
        public SCHEDULER()
        {
            this.DETAILS_SCHEDULER = new HashSet<DETAILS_SCHEDULER>();
            this.HISTORY_SCHEDULER = new HashSet<HISTORY_SCHEDULER>();
            this.ROOM_SCHEDULER = new HashSet<ROOM_SCHEDULER>();
            this.SCHEDULER_CHART = new HashSet<SCHEDULER_CHART>();
        }
    
        public int ID_SCHE { get; set; }
        public Nullable<System.DateTime> STA_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> ALL_DAY { get; set; }
        public string TIT_SCHE { get; set; }
        public Nullable<int> ID_REPE { get; set; }
        public Nullable<int> REP_EVER { get; set; }
        public Nullable<int> REP_ON { get; set; }
        public Nullable<int> ID_REPE_END { get; set; }
        public string REPE_END_VALU { get; set; }
        public Nullable<System.DateTime> END_SCHE { get; set; }
        public string DES_SCHE { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> ID_RECURRENCE { get; set; }
        public string EXP_RECURRENCE { get; set; }
        public Nullable<int> ID_PERS_ENTI_DELE { get; set; }
    
        public virtual ICollection<DETAILS_SCHEDULER> DETAILS_SCHEDULER { get; set; }
        public virtual ICollection<HISTORY_SCHEDULER> HISTORY_SCHEDULER { get; set; }
        public virtual REPEAT REPEAT { get; set; }
        public virtual REPEAT_END REPEAT_END { get; set; }
        public virtual ICollection<ROOM_SCHEDULER> ROOM_SCHEDULER { get; set; }
        public virtual ICollection<SCHEDULER_CHART> SCHEDULER_CHART { get; set; }
    }
}
