//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesNow
    {
        public int id_servicesNow { get; set; }
        public string GrupoDeAsignacion { get; set; }
        public string BreveDescripcion { get; set; }
        public string AtribuidoA { get; set; }
        public string Numero { get; set; }
        public string Prioridad { get; set; }
        public string MotivoPonerEspera { get; set; }
        public Nullable<int> TiempoResolucion { get; set; }
        public string Categoria { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> Abierto { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string UnidadNegocio { get; set; }
        public string Solicitante { get; set; }
        public string Canal { get; set; }
        public Nullable<System.DateTime> Actualizado { get; set; }
        public string EstadoIncidencia { get; set; }
        public string AbiertoPor { get; set; }
        public string SubCategoria { get; set; }
        public string CerradoPor { get; set; }
        public string ActualizadoPor { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
