//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITE
    {
        public SITE()
        {
            this.LOCATIONs = new HashSet<LOCATION>();
            this.SedexGrupo = new HashSet<SedexGrupo>();
        }
    
        public int ID_SITE { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public string NAM_SITE { get; set; }
        public string COLOR { get; set; }
        public Nullable<int> IdCompania { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ICollection<LOCATION> LOCATIONs { get; set; }
        public virtual ICollection<SedexGrupo> SedexGrupo { get; set; }
    }
}
