//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLA
    {
        public SLA()
        {
            this.SoporteEDs = new HashSet<SoporteED>();
            this.PROYECTO_SLA = new HashSet<PROYECTO_SLA>();
            this.TICKETs = new HashSet<TICKET>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<int> ID_TYPE_TICK { get; set; }
    
        public virtual ICollection<SoporteED> SoporteEDs { get; set; }
        public virtual TYPE_TICKET TYPE_TICKET { get; set; }
        public virtual ICollection<PROYECTO_SLA> PROYECTO_SLA { get; set; }
        public virtual ICollection<TICKET> TICKETs { get; set; }
    }
}
