//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPersonal
    {
        public SolicitudPersonal()
        {
            this.Candidato = new HashSet<Candidato>();
            this.RecursosAdicionales = new HashSet<RecursosAdicionales>();
            this.RecursosTecnologicos = new HashSet<RecursosTecnologicos>();
            this.RequisitoAdicionalSolicitud = new HashSet<RequisitoAdicionalSolicitud>();
            this.SolicitudRechazado = new HashSet<SolicitudRechazado>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdMotivoVacante { get; set; }
        public Nullable<int> IdEstadoSolicitud { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> IdTipoContrato { get; set; }
        public Nullable<int> IdGerencia { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> IdJefeInmediato { get; set; }
        public Nullable<int> IdPersonaReemplaza { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public Nullable<int> IdAprobacion { get; set; }
        public Nullable<decimal> Remuneracion { get; set; }
        public string Beneficio { get; set; }
        public Nullable<int> CantidadVacante { get; set; }
        public Nullable<System.DateTime> FechaInicioTrabajo { get; set; }
        public Nullable<System.DateTime> FechaFinTrabajo { get; set; }
        public string Justificacion { get; set; }
        public string Requisitos { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public bool Estado { get; set; }
        public string DuracionContrato { get; set; }
        public string Especificar { get; set; }
        public string PerfilTipo { get; set; }
        public string JustificacionRecurso { get; set; }
        public string Carpeta { get; set; }
        public Nullable<bool> Lectura { get; set; }
        public Nullable<bool> Modificar { get; set; }
        public Nullable<decimal> Presupuesto { get; set; }
        public Nullable<System.DateTime> FechaFinProyecto { get; set; }
        public string Modalidad { get; set; }
        public string UbicacionModalidad { get; set; }
        public string RecursoInformatico { get; set; }
        public string RecursoComunicacion { get; set; }
    
        public virtual ICollection<Candidato> Candidato { get; set; }
        public virtual EstadoSolicitud EstadoSolicitud { get; set; }
        public virtual MotivoVacante MotivoVacante { get; set; }
        public virtual ICollection<RecursosAdicionales> RecursosAdicionales { get; set; }
        public virtual ICollection<RecursosTecnologicos> RecursosTecnologicos { get; set; }
        public virtual ICollection<RequisitoAdicionalSolicitud> RequisitoAdicionalSolicitud { get; set; }
        public virtual ICollection<SolicitudRechazado> SolicitudRechazado { get; set; }
    }
}
