//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoporteED
    {
        public SoporteED()
        {
            this.Facturacions = new HashSet<Facturacion>();
            this.SoporteEDDetalles = new HashSet<SoporteEDDetalle>();
            this.MarcasdeSoporteED = new HashSet<MarcasdeSoporteED>();
        }
    
        public int IdSoporteED { get; set; }
        public Nullable<int> IdDocuSale { get; set; }
        public Nullable<bool> MantPeriodico { get; set; }
        public string Solucion { get; set; }
        public Nullable<decimal> TiempoSoporte { get; set; }
        public Nullable<int> IdSLA { get; set; }
        public Nullable<int> MantenimientoPrev { get; set; }
        public Nullable<System.DateTime> FinSoporte { get; set; }
        public Nullable<int> BolsaHoras { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdManu { get; set; }
        public string Frecuencia { get; set; }
        public Nullable<System.DateTime> InicioSoporte { get; set; }
    
        public virtual MANUFACTURER MANUFACTURER { get; set; }
        public virtual SLA SLA { get; set; }
        public virtual ICollection<Facturacion> Facturacions { get; set; }
        public virtual ICollection<SoporteEDDetalle> SoporteEDDetalles { get; set; }
        public virtual DOCUMENT_SALE DOCUMENT_SALE { get; set; }
        public virtual ICollection<MarcasdeSoporteED> MarcasdeSoporteED { get; set; }
    }
}
