//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoporteFabricante
    {
        public SoporteFabricante()
        {
            this.SoporteFabricanteDetalles = new HashSet<SoporteFabricanteDetalle>();
            this.ProductosProyecto = new HashSet<ProductosProyecto>();
        }
    
        public int IdSoporteFAB { get; set; }
        public Nullable<int> IdDocuSale { get; set; }
        public Nullable<int> IdManu { get; set; }
        public Nullable<int> TiempoSoporte { get; set; }
        public Nullable<bool> MantPeriodico { get; set; }
        public Nullable<int> MantenimientoPrev { get; set; }
        public Nullable<System.DateTime> FinSoporte { get; set; }
        public string Productos { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> InicioSoporte { get; set; }
        public string RMA { get; set; }
    
        public virtual MANUFACTURER MANUFACTURER { get; set; }
        public virtual ICollection<SoporteFabricanteDetalle> SoporteFabricanteDetalles { get; set; }
        public virtual DOCUMENT_SALE DOCUMENT_SALE { get; set; }
        public virtual ICollection<ProductosProyecto> ProductosProyecto { get; set; }
    }
}
