//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCE
    {
        public SOURCE()
        {
            this.TICKETs = new HashSet<TICKET>();
        }
    
        public int ID_SOUR { get; set; }
        public string NAM_SOUR { get; set; }
        public string DES_SOUR { get; set; }
        public Nullable<bool> VIG_SOUR { get; set; }
    
        public virtual ICollection<TICKET> TICKETs { get; set; }
    }
}
