//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS
    {
        public STATUS()
        {
            this.TICKET_STATUS_CONDITION = new HashSet<TICKET_STATUS_CONDITION>();
            this.TICKET_STATUS_CONDITION1 = new HashSet<TICKET_STATUS_CONDITION>();
            this.QUEUEs = new HashSet<QUEUE>();
            this.TICKETs = new HashSet<TICKET>();
            this.TICKETs1 = new HashSet<TICKET>();
        }
    
        public int ID_STAT { get; set; }
        public string NAM_STAT { get; set; }
        public string NAM_GRAP_STAT { get; set; }
        public string COL_GRAP_STAT { get; set; }
        public string COL_INDV_STAT { get; set; }
        public string DES_STAT { get; set; }
        public Nullable<bool> VIS_STAT { get; set; }
        public Nullable<bool> VIG_STAT { get; set; }
        public string CLA_STAT { get; set; }
        public Nullable<int> ORD_STAT { get; set; }
        public Nullable<bool> VIS_CHAN { get; set; }
        public Nullable<bool> VIS_NEW_TICKET { get; set; }
        public Nullable<bool> DIFERENTIAL { get; set; }
    
        public virtual ICollection<TICKET_STATUS_CONDITION> TICKET_STATUS_CONDITION { get; set; }
        public virtual ICollection<TICKET_STATUS_CONDITION> TICKET_STATUS_CONDITION1 { get; set; }
        public virtual ICollection<QUEUE> QUEUEs { get; set; }
        public virtual ICollection<TICKET> TICKETs { get; set; }
        public virtual ICollection<TICKET> TICKETs1 { get; set; }
    }
}
