//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_REQUEST_EXPENSE
    {
        public STATUS_REQUEST_EXPENSE()
        {
            this.REQUEST_EXPENSE = new HashSet<REQUEST_EXPENSE>();
        }
    
        public int ID_STAT_REQU_EXPE { get; set; }
        public string NAM_STAT_REQU_EXPE { get; set; }
        public string NAM_STAT_REQU_EXPE_SPAN { get; set; }
        public string DES_STAT_REQU_EXPE { get; set; }
        public string COLOR { get; set; }
        public string NAM_ABBR { get; set; }
        public Nullable<int> ORD_STAT { get; set; }
        public Nullable<bool> AFF_PETT_CASH_AVAI { get; set; }
        public Nullable<bool> AFF_PETT_CASH_REMA { get; set; }
    
        public virtual ICollection<REQUEST_EXPENSE> REQUEST_EXPENSE { get; set; }
    }
}
