//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_ASSET
    {
        public STATUS_ASSET()
        {
            this.CONDITIONs = new HashSet<CONDITION>();
        }
    
        public int ID_STAT_ASSE { get; set; }
        public string NAM_STAT_ASSE { get; set; }
        public string COL_STAT_ASSE { get; set; }
    
        public virtual ICollection<CONDITION> CONDITIONs { get; set; }
    }
}
