//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_OBJETIVES
    {
        public STATUS_OBJETIVES()
        {
            this.OBJETIVES = new HashSet<OBJETIVE>();
        }
    
        public int ID_STAT_OBJE { get; set; }
        public string NAM_STAT_OBJE { get; set; }
        public string DES_STAT_OBJE { get; set; }
        public Nullable<bool> VIG_STAT_OBJE { get; set; }
    
        public virtual ICollection<OBJETIVE> OBJETIVES { get; set; }
    }
}
