//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_TICKET
    {
        public int ID_STAT_TICK { get; set; }
        public string NAM_STAT_TICK { get; set; }
        public string NAM_GRAP_STAT_TICK { get; set; }
        public string COL_GRAP_STAT_TICK { get; set; }
        public string COL_INDV_STAT_TICK { get; set; }
        public string DES_STAT_TICK { get; set; }
        public Nullable<bool> VIS_STAT_TICK { get; set; }
        public Nullable<bool> VIG_STAT_TICK { get; set; }
        public string CLA_STAT_TICK { get; set; }
        public Nullable<int> ORD_STAT_TICK { get; set; }
        public Nullable<bool> VIS_CHAN { get; set; }
        public Nullable<bool> VIS_NEW_TICKET { get; set; }
        public Nullable<bool> DIFERENTIAL { get; set; }
    }
}
