//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBTYPE_ACTITY
    {
        public int ID_SUBTYPE_ACT { get; set; }
        public int ID_TYPE_ACT { get; set; }
        public string DES_SUB_TYPE { get; set; }
        public Nullable<bool> VIG_SUB_TYPE { get; set; }
    }
}
