//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTipoComponente
    {
        public SubTipoComponente()
        {
            this.ComponenteStockCabecera = new HashSet<ComponenteStockCabecera>();
        }
    
        public int IdSubtComp { get; set; }
        public Nullable<int> IdComponente { get; set; }
        public Nullable<int> IdTipoActivo { get; set; }
        public Nullable<int> IdAcco { get; set; }
        public string NomSubtComp { get; set; }
        public string DesSubtComp { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Componente Componente { get; set; }
        public virtual TYPE_ASSET TYPE_ASSET { get; set; }
        public virtual ICollection<ComponenteStockCabecera> ComponenteStockCabecera { get; set; }
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
