//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY
    {
        public SURVEY()
        {
            this.QUESTION_GROUP = new HashSet<QUESTION_GROUP>();
        }
    
        public int ID_SURV { get; set; }
        public Nullable<int> ID_TYPE_SURV { get; set; }
        public string NAM_SURV { get; set; }
        public Nullable<System.DateTime> DAT_STAR { get; set; }
        public Nullable<System.DateTime> DAT_END { get; set; }
        public Nullable<bool> VIG_TYPE_SURV { get; set; }
    
        public virtual ICollection<QUESTION_GROUP> QUESTION_GROUP { get; set; }
    }
}
