//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY_STATUS
    {
        public SURVEY_STATUS()
        {
            this.SURVEY_TICKET = new HashSet<SURVEY_TICKET>();
        }
    
        public int ID_SURV_STAT { get; set; }
        public string NAM_SURV_STAT { get; set; }
    
        public virtual ICollection<SURVEY_TICKET> SURVEY_TICKET { get; set; }
    }
}
