//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_OPER_TYPE_ASSE
    {
        public SYSTEM_OPER_TYPE_ASSE()
        {
            this.ASSETs = new HashSet<ASSET>();
        }
    
        public int ID_SYST_OPER_TYPE_ASSE { get; set; }
        public Nullable<int> ID_TYPE_ASSE { get; set; }
        public Nullable<int> ID_SYST_OPER { get; set; }
        public Nullable<bool> VIG_SYST_OPER_TYPE_ASSE { get; set; }
    
        public virtual SYSTEM_OPERATING SYSTEM_OPERATING { get; set; }
        public virtual TYPE_ASSET TYPE_ASSET { get; set; }
        public virtual ICollection<ASSET> ASSETs { get; set; }
    }
}
