//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_OPERATING
    {
        public SYSTEM_OPERATING()
        {
            this.SYSTEM_OPER_TYPE_ASSE = new HashSet<SYSTEM_OPER_TYPE_ASSE>();
        }
    
        public int ID_SYST_OPER { get; set; }
        public string NAM_SYST_OPER { get; set; }
        public string DESC_SYST_OPER { get; set; }
        public Nullable<bool> VIG_SYST_OPER { get; set; }
    
        public virtual ICollection<SYSTEM_OPER_TYPE_ASSE> SYSTEM_OPER_TYPE_ASSE { get; set; }
    }
}
