//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaDetalle
    {
        public int IdTareaDetalle { get; set; }
        public Nullable<int> Id_Tick { get; set; }
        public Nullable<int> IdTarea { get; set; }
        public Nullable<int> Id_Pers_Enti { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaTareaTerminada { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public Nullable<System.DateTime> CREATED_MAIL { get; set; }
        public Nullable<int> Id_Queu { get; set; }
        public string Cod_Tarea { get; set; }
        public Nullable<int> IdSedeImpu { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string CeCoImpu { get; set; }
        public string PartPresup { get; set; }
        public Nullable<System.DateTime> FechaEjecutada { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<int> IdUsuarioSap { get; set; }
        public Nullable<int> IdGrupoAutoriza { get; set; }
    
        public virtual EstadoTarea EstadoTarea { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
