//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public Tarea()
        {
            this.TareaDetalle = new HashSet<TareaDetalle>();
        }
    
        public int IdTarea { get; set; }
        public Nullable<int> Id_Cate { get; set; }
        public string DescripcionTarea { get; set; }
        public string TipoGestion { get; set; }
        public Nullable<int> Id_Queu { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
        public Nullable<int> UsuarioActualiza { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string TituloTarea { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> IdCateTarea { get; set; }
        public Nullable<int> IdTareaPadre { get; set; }
        public string DescPendiente { get; set; }
        public Nullable<int> GrupoTarea { get; set; }
    
        public virtual QUEUE QUEUE { get; set; }
        public virtual ICollection<TareaDetalle> TareaDetalle { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual CategoriaConTareas CategoriaConTareas { get; set; }
    }
}
