//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARGET_SEGMENT
    {
        public int ID_TARG_SEGM { get; set; }
        public Nullable<int> ID_TARGET { get; set; }
        public Nullable<int> ID_SEGM { get; set; }
        public Nullable<decimal> VAL_SUP_TARG_SEGM { get; set; }
        public Nullable<decimal> VAL_INF_TARG_SEGM { get; set; }
    
        public virtual SEGMENT SEGMENT { get; set; }
        public virtual TARGET TARGET { get; set; }
    }
}
