//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAutomatico
    {
        public TicketAutomatico()
        {
            this.TicketAutomaticoDias = new HashSet<TicketAutomaticoDia>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTicket { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public Nullable<int> Dia { get; set; }
        public Nullable<int> Vigencia { get; set; }
        public Nullable<System.DateTime> VigenciaFechaInicio { get; set; }
        public Nullable<System.DateTime> VigenciaFechaFin { get; set; }
        public Nullable<System.DateTime> HoraCreacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> IdCuenta { get; set; }
    
        public virtual ICollection<TicketAutomaticoDia> TicketAutomaticoDias { get; set; }
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual TICKET TICKET { get; set; }
    }
}
