//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_STATUS
    {
        public int ID_TICK_STAT { get; set; }
        public string NAM_TICK_STAT { get; set; }
        public string NAM_TICK_STAT_GROU { get; set; }
        public string COL_TICK_STAT_GROU { get; set; }
        public string COL_TICK_STAT_INDV { get; set; }
        public string DES_TICK_STAT { get; set; }
        public Nullable<bool> VIS_TICK_STAT { get; set; }
        public Nullable<bool> VIG_TICK_STAT { get; set; }
        public string CLA_TICK_STAT { get; set; }
        public Nullable<int> ORD_TICK_STAT { get; set; }
        public bool VIS_NEW_TICK { get; set; }
        public bool IS_WORK { get; set; }
        public Nullable<int> ID_COLO_TEMP { get; set; }
        public Nullable<int> ID_COLO_TEMP_GROU { get; set; }
    }
}
