//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public TICKET()
        {
            this.ASSETs = new HashSet<ASSET>();
            this.ATTACHEDs = new HashSet<ATTACHED>();
            this.CHANGE_REQUEST = new HashSet<CHANGE_REQUEST>();
            this.FEEDBACKs = new HashSet<FEEDBACK>();
            this.CodigoSMS = new HashSet<CodigoSMS>();
            this.TicketAutomaticoes = new HashSet<TicketAutomatico>();
            this.TICKET_NOTIFICATION = new HashSet<TICKET_NOTIFICATION>();
        }
    
        public int ID_TICK { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> ID_TYPE_TICK { get; set; }
        public Nullable<int> ID_CLIE { get; set; }
        public Nullable<int> ID_AFEC_END_CLIE { get; set; }
        public Nullable<int> ID_AREA { get; set; }
        public Nullable<int> ID_QUEU { get; set; }
        public Nullable<int> ID_PRIO { get; set; }
        public Nullable<int> ID_STAT { get; set; }
        public Nullable<int> ID_STAT_END { get; set; }
        public Nullable<int> ID_ASSI { get; set; }
        public Nullable<int> ID_SUBC { get; set; }
        public Nullable<int> ID_SUBS { get; set; }
        public Nullable<int> ID_SOUR { get; set; }
        public Nullable<System.DateTime> FEC_TICK { get; set; }
        public Nullable<System.DateTime> FEC_INI_TICK { get; set; }
        public Nullable<System.DateTime> REP_TICK { get; set; }
        public string COD_TICK { get; set; }
        public string SUM_TICK { get; set; }
        public Nullable<bool> REM_CTRL_TICK { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CREATE_TICK { get; set; }
        public Nullable<System.DateTime> MODIFIED_TICK { get; set; }
        public Nullable<System.DateTime> DELETE_TICK { get; set; }
        public Nullable<System.DateTime> FOR_REP { get; set; }
        public Nullable<int> ID_TICK_PARENT { get; set; }
        public Nullable<bool> IS_PARENT { get; set; }
        public Nullable<bool> IS_ROLE_USER { get; set; }
        public Nullable<int> ID_COMP { get; set; }
        public Nullable<int> ID_COMP_END { get; set; }
        public Nullable<int> ID_DOCU_SALE { get; set; }
        public Nullable<int> ID_DETA_DOCU_SALE { get; set; }
        public Nullable<int> ID_DETA_SALE { get; set; }
        public Nullable<int> ID_CATE { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<int> ID_PERS_ENTI_END { get; set; }
        public Nullable<int> ID_PERS_ENTI_ASSI { get; set; }
        public Nullable<int> ID_ASSE { get; set; }
        public Nullable<int> ID_TYPE_FORM { get; set; }
        public Nullable<int> ID_LOCA { get; set; }
        public Nullable<int> MINUTES { get; set; }
        public Nullable<System.DateTime> DAT_EXPI_TICK { get; set; }
        public Nullable<int> ID_ALER_MAIL_TICK { get; set; }
        public Nullable<int> ID_PERS_ENTI_ASSI_STAR { get; set; }
        public Nullable<int> ID_STAT_SALE_OPPO { get; set; }
        public Nullable<decimal> AMM_SALE_OPPO { get; set; }
        public Nullable<bool> SEND_SURVEY { get; set; }
        public Nullable<bool> SEND_MAIL { get; set; }
        public Nullable<System.DateTime> CREATED_MAIL { get; set; }
        public Nullable<int> ID_ENTI_CREADTED { get; set; }
        public Nullable<int> ID_ENTI_REQU { get; set; }
        public Nullable<int> ID_ENTI_END { get; set; }
        public Nullable<int> ID_ENTI_ASSI { get; set; }
        public Nullable<int> ID_CIA { get; set; }
        public string TITLE_TICK { get; set; }
        public Nullable<bool> SERVICE { get; set; }
        public Nullable<System.DateTime> FEC_INI_REAL { get; set; }
        public Nullable<int> IdTema { get; set; }
        public Nullable<bool> EsperaPorCliente { get; set; }
        public Nullable<bool> FlagProblema { get; set; }
        public Nullable<int> IdMantED { get; set; }
        public Nullable<int> IdMantFAB { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<System.DateTime> FechaRecepcionSolicitud { get; set; }
        public Nullable<int> IdInforme { get; set; }
        public string Adicional1 { get; set; }
        public string Adicional2 { get; set; }
        public string TicketExterno { get; set; }
        public Nullable<int> IdSLA { get; set; }
        public Nullable<int> IdProyectoSLA { get; set; }
        public string SubCuenta { get; set; }
        public Nullable<bool> Afec_Servi { get; set; }
        public string Observaciones { get; set; }
        public string Analisis_Causa { get; set; }
        public string RMA { get; set; }
        public Nullable<bool> FlagModifica { get; set; }
        public Nullable<System.DateTime> MODIFIED_REPORTTICK { get; set; }
        public Nullable<int> IdRazon { get; set; }
        public Nullable<int> IdModTrabajo { get; set; }
        public string Solman { get; set; }
        public Nullable<int> IdTipoPase { get; set; }
        public Nullable<int> ID_PERS_ENTI_ANLT { get; set; }
        public string Solucion { get; set; }
        public Nullable<int> IdGrupoReportador { get; set; }
        public Nullable<System.DateTime> FechaInicioReal { get; set; }
        public Nullable<bool> SEND_MAIL_TAREA { get; set; }
        public Nullable<bool> EnvioCorreoSLA { get; set; }
        public Nullable<System.DateTime> CrearCorreoSLA { get; set; }
        public Nullable<bool> EnvioCorreoAltaBaja { get; set; }
        public string EstadoEncuesta { get; set; }
        public Nullable<int> IdProveedorMovil { get; set; }
        public Nullable<int> IdGrupoActivo { get; set; }
        public string TAG { get; set; }
        public Nullable<int> IdMotivoEstado { get; set; }
        public string GarantiaProveedor { get; set; }
        public string ImpactoServicio { get; set; }
        public Nullable<bool> ConsumoHoras { get; set; }
        public Nullable<int> MinutosEfectivos { get; set; }
        public Nullable<int> IdMotivoSource { get; set; }
        public Nullable<int> UsuarioVIP { get; set; }
        public Nullable<bool> RegistroTiempoAtencion { get; set; }
        public Nullable<int> FalsoPositivo { get; set; }
    
        public virtual ACCOUNT_PARAMETER ACCOUNT_PARAMETER { get; set; }
        public virtual ICollection<ASSET> ASSETs { get; set; }
        public virtual ICollection<ATTACHED> ATTACHEDs { get; set; }
        public virtual ICollection<CHANGE_REQUEST> CHANGE_REQUEST { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual CLIENT CLIENT1 { get; set; }
        public virtual CLIENT CLIENT2 { get; set; }
        public virtual ICollection<FEEDBACK> FEEDBACKs { get; set; }
        public virtual PRIORITY PRIORITY { get; set; }
        public virtual QUEUE QUEUE { get; set; }
        public virtual SLA SLA { get; set; }
        public virtual SOURCE SOURCE { get; set; }
        public virtual STATUS STATUS { get; set; }
        public virtual STATUS STATUS1 { get; set; }
        public virtual ICollection<CodigoSMS> CodigoSMS { get; set; }
        public virtual ICollection<TicketAutomatico> TicketAutomaticoes { get; set; }
        public virtual ICollection<TICKET_NOTIFICATION> TICKET_NOTIFICATION { get; set; }
        public virtual TYPE_TICKET TYPE_TICKET { get; set; }
    }
}
