//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_NOTIFICATION
    {
        public int ID_TICK_NOTI { get; set; }
        public Nullable<int> ID_TICK { get; set; }
        public Nullable<int> ID_TYPE_NOTI { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
    
        public virtual TYPE_NOTIFICATION TYPE_NOTIFICATION { get; set; }
        public virtual TICKET TICKET { get; set; }
    }
}
