//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAtencion
    {
        public int id_TipoAtencion { get; set; }
        public string TipoAtencion1 { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
