//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    
    public partial class tktInformeNivel2_Result1
    {
        public Nullable<int> ID_COMP { get; set; }
        public Nullable<int> ID_DOCU_SALE { get; set; }
        public Nullable<int> ID_QUEU { get; set; }
        public Nullable<int> ID_COMP_END { get; set; }
    }
}
