//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public int ID_TRAN { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
        public Nullable<int> ID_CATE_TRAN { get; set; }
        public string COD_TRAN { get; set; }
        public Nullable<int> ID_ACCO_MONT { get; set; }
        public Nullable<decimal> AMO_TRANS { get; set; }
        public string DES_TRANS { get; set; }
        public Nullable<System.DateTime> DAT_TRAN { get; set; }
        public Nullable<System.DateTime> CREATE_TRAN { get; set; }
        public Nullable<System.DateTime> MODIFIED_TRAN { get; set; }
        public Nullable<decimal> IGV_TRAN { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> TYP_CHAN { get; set; }
    
        public virtual ACCOUNTING_MONTH ACCOUNTING_MONTH { get; set; }
        public virtual CATEGORY_TRANSACTION CATEGORY_TRANSACTION { get; set; }
    }
}
