//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_DELI_SUST
    {
        public TYPE_DELI_SUST()
        {
            this.DELIVERY_SUSTAIN = new HashSet<DELIVERY_SUSTAIN>();
            this.REQUEST_EXPENSE = new HashSet<REQUEST_EXPENSE>();
        }
    
        public int ID_TYPE_DELI_SUST { get; set; }
        public string NAM_TYPE_DELI_SUST { get; set; }
        public string NAM_TYPE_DELI_SUST_SPAN { get; set; }
        public string DES_TYPE_DELI_SUST { get; set; }
        public Nullable<bool> VIG_TYPE_DELI_SUST { get; set; }
    
        public virtual ICollection<DELIVERY_SUSTAIN> DELIVERY_SUSTAIN { get; set; }
        public virtual ICollection<REQUEST_EXPENSE> REQUEST_EXPENSE { get; set; }
    }
}
