//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_DETAILS_TICKET
    {
        public TYPE_DETAILS_TICKET()
        {
            this.DETAILS_TICKET = new HashSet<DETAILS_TICKET>();
        }
    
        public int ID_TYPE_DETA_TICK { get; set; }
        public string NAM_TYPE_DETA_TICK { get; set; }
        public string DES_TYPE_DETA_TICK { get; set; }
        public Nullable<bool> VIG_TYPE_DETA_TICK { get; set; }
        public Nullable<bool> VIS_TYPE_DETA_TICK { get; set; }
    
        public virtual ICollection<DETAILS_TICKET> DETAILS_TICKET { get; set; }
    }
}
