//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_DOCUMENT_MODULE
    {
        public int ID_TYPE_DOCU_MODU { get; set; }
        public int ID_TYPE_DOCU_ATTA { get; set; }
        public Nullable<bool> VIG_TYPE_DOCU_MODU { get; set; }
        public Nullable<int> ID_MODU { get; set; }
    }
}
