//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_REGISTER
    {
        public TYPE_REGISTER()
        {
            this.ON_VERIFY = new HashSet<ON_VERIFY>();
        }
    
        public int ID_TYPE_REGI { get; set; }
        public string NAM_TYPE_REGI { get; set; }
        public string DES_TYPE_REGI { get; set; }
        public Nullable<bool> VAL_TYPE_REGI { get; set; }
    
        public virtual ICollection<ON_VERIFY> ON_VERIFY { get; set; }
    }
}
