//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_NOTIFICATION
    {
        public TYPE_NOTIFICATION()
        {
            this.TICKET_NOTIFICATION = new HashSet<TICKET_NOTIFICATION>();
        }
    
        public int ID_TYPE_NOTI { get; set; }
        public string NAM_TYPE_NOTI { get; set; }
        public string DES_TYPE_NOTI { get; set; }
    
        public virtual ICollection<TICKET_NOTIFICATION> TICKET_NOTIFICATION { get; set; }
    }
}
