//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_ATTACH_PROJECT
    {
        public TYPE_ATTACH_PROJECT()
        {
            this.ATTACHED_PROJECT = new HashSet<ATTACHED_PROJECT>();
        }
    
        public int ID_TYPE_ATTA_PROJ { get; set; }
        public string NAM_ATTA_PROJ { get; set; }
        public string DES_ATTA_PROJ { get; set; }
    
        public virtual ICollection<ATTACHED_PROJECT> ATTACHED_PROJECT { get; set; }
    }
}
