//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_HITO
    {
        public TYPE_HITO()
        {
            this.HITOes = new HashSet<HITO>();
        }
    
        public int ID_TYPE_HITO { get; set; }
        public string NAM_TYPE_HITO { get; set; }
        public string DES_TYPE_HITO { get; set; }
        public Nullable<decimal> SCA_TYPE_HITO { get; set; }
    
        public virtual ICollection<HITO> HITOes { get; set; }
    }
}
