//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_DOCUMENT_EXPENSE
    {
        public TYPE_DOCUMENT_EXPENSE()
        {
            this.DOCUMENT_EXPENSE = new HashSet<DOCUMENT_EXPENSE>();
        }
    
        public int ID_TYPE_DOCU_EXPE { get; set; }
        public string NAM_DOCU { get; set; }
        public Nullable<bool> VIG_DOCU { get; set; }
        public Nullable<bool> AFF_AVAI { get; set; }
        public string TIPO_SUNAT { get; set; }
    
        public virtual ICollection<DOCUMENT_EXPENSE> DOCUMENT_EXPENSE { get; set; }
    }
}
