//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_ACT_LOG
    {
        public int ID_TYPE_ACT { get; set; }
        public string DES_ACT { get; set; }
        public Nullable<bool> VIG_ACT { get; set; }
        public Nullable<int> ID_ACCO { get; set; }
    }
}
