//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_DOCUMENT_SALE
    {
        public TYPE_DOCUMENT_SALE()
        {
            this.DOCUMENT_SALE = new HashSet<DOCUMENT_SALE>();
        }
    
        public int ID_TYPE_DOCU_SALE { get; set; }
        public string COD_TYPE_DOCU_SALE { get; set; }
        public string NAM_TYPE_DOCU_SALE { get; set; }
        public Nullable<bool> VIG_TYPE_DOCU_SALE { get; set; }
    
        public virtual ICollection<DOCUMENT_SALE> DOCUMENT_SALE { get; set; }
    }
}
