//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_FORMAT
    {
        public TYPE_FORMAT()
        {
            this.DELIVERY_RECEPTION = new HashSet<DELIVERY_RECEPTION>();
        }
    
        public int ID_TYPE_FORM { get; set; }
        public string NAM_TYPE_FORM { get; set; }
        public string DES_TYPE_FORM { get; set; }
    
        public virtual ICollection<DELIVERY_RECEPTION> DELIVERY_RECEPTION { get; set; }
    }
}
