//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_CLIENT
    {
        public TYPE_CLIENT()
        {
            this.PERSON_ENTITY = new HashSet<PERSON_ENTITY>();
        }
    
        public int ID_TYPE_CLIE { get; set; }
        public string NAM_TYPE_CLIE { get; set; }
        public string DES_TYPE_CLIE { get; set; }
        public Nullable<int> ID_PRIO { get; set; }
    
        public virtual ICollection<PERSON_ENTITY> PERSON_ENTITY { get; set; }
    }
}
