//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_ABSENCE
    {
        public TYPE_ABSENCE()
        {
            this.ABSENCEs = new HashSet<ABSENCE>();
        }
    
        public int ID_TYPE_ABSE { get; set; }
        public string NAM_TYPE_ABSE { get; set; }
        public string DES_TYPE_ABSE { get; set; }
    
        public virtual ICollection<ABSENCE> ABSENCEs { get; set; }
    }
}
