//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL_EXTERNAL
    {
        public int ID_URL { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public string URL { get; set; }
        public string NAM_URL { get; set; }
        public string DESC_URL { get; set; }
        public Nullable<bool> VIG_URL { get; set; }
    }
}
