//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.UsuarioPerfils = new HashSet<UsuarioPerfil>();
            this.UsuarioAccion = new HashSet<UsuarioAccion>();
            this.Institucion = new HashSet<Institucion>();
            this.Institucion1 = new HashSet<Institucion>();
        }
    
        public int Id { get; set; }
        public string Usuario1 { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> FechaCambioPassword { get; set; }
        public Nullable<int> IntentosFallidos { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<int> CodigoIdioma { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> FechaUltimoAcceso { get; set; }
        public Nullable<int> IdIdioma { get; set; }
    
        public virtual ICollection<UsuarioPerfil> UsuarioPerfils { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual ICollection<UsuarioAccion> UsuarioAccion { get; set; }
        public virtual ICollection<Institucion> Institucion { get; set; }
        public virtual ICollection<Institucion> Institucion1 { get; set; }
    }
}
