//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Employees
    {
        public int ID_PERS_CONT { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public Nullable<System.DateTime> STAR_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string FIR_NAME { get; set; }
        public string LAS_NAME { get; set; }
        public string MOT_NAME { get; set; }
        public string NAM_LOCA { get; set; }
        public string NAM_SITE { get; set; }
        public string CODE { get; set; }
    }
}
