//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACATION_AND_ABSENCE
    {
        public int ID_VACA_ABSE { get; set; }
        public Nullable<int> ID_VACA { get; set; }
        public Nullable<int> ID_ABSE { get; set; }
        public Nullable<System.DateTime> DAT_VACA_ABSE { get; set; }
        public Nullable<int> ID_STAT_VACA { get; set; }
        public Nullable<int> NUM_DAY { get; set; }
        public Nullable<int> ID_HORA { get; set; }
        public Nullable<int> ID_TYPE_REGI { get; set; }
        public Nullable<int> ID_PERS_ENTI { get; set; }
        public string NUM_TYPE_DI { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
    }
}
