//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_PERIOD
    {
        public WORK_PERIOD()
        {
            this.PERSON_CONTRACT = new HashSet<PERSON_CONTRACT>();
            this.PROVISION_VACATION = new HashSet<PROVISION_VACATION>();
        }
    
        public int ID_WORK_PERI { get; set; }
        public Nullable<int> ID_PERS_CONT { get; set; }
        public Nullable<System.DateTime> STAR_DATE { get; set; }
        public Nullable<System.DateTime> CESS_DATE { get; set; }
        public Nullable<int> ID_REAS_END { get; set; }
        public string NAM_ATTA { get; set; }
        public Nullable<bool> INDEFINITE { get; set; }
        public Nullable<int> TOTAL_YEAR { get; set; }
        public Nullable<int> TOTAL_MONTH { get; set; }
        public Nullable<int> TOTAL_DAY { get; set; }
    
        public virtual ICollection<PERSON_CONTRACT> PERSON_CONTRACT { get; set; }
        public virtual ICollection<PROVISION_VACATION> PROVISION_VACATION { get; set; }
        public virtual REASON_END_PERIOD REASON_END_PERIOD { get; set; }
    }
}
