//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPElectrodata.Models
{
    using System;
    
    public partial class WORK_LOAD_STATUS_Result1
    {
        public string EMPLOYEE { get; set; }
        public Nullable<int> ID_PERS_ENTI_ASSI { get; set; }
        public Nullable<int> QUA_TICK { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public string ACTIVE_COLOR { get; set; }
        public Nullable<int> CANCELLED { get; set; }
        public string CANCELLED_COLOR { get; set; }
        public Nullable<int> RESOLVED { get; set; }
        public string RESOLVED_COLOR { get; set; }
        public Nullable<int> SCHEDULED { get; set; }
        public string SCHEDULED_COLOR { get; set; }
        public Nullable<int> CLOSED { get; set; }
        public string CLOSED_COLOR { get; set; }
    }
}
