//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_TICKET
    {
        public int ID_QUES_TICK { get; set; }
        public Nullable<int> ID_QUES { get; set; }
        public Nullable<int> ID_SURV_TICK { get; set; }
        public string VAL_QUES_TICK { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
    
        public virtual SURVEY_TICKET SURVEY_TICKET { get; set; }
    }
}
