//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_TYPE
    {
        public QUESTION_TYPE()
        {
            this.QUESTIONs = new HashSet<QUESTION>();
        }
    
        public int ID_QUES_TYPE { get; set; }
        public string NAM_QUES_TYPE { get; set; }
    
        public virtual ICollection<QUESTION> QUESTIONs { get; set; }
    }
}
