//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_OPTION
    {
        public int ID_QUES_OPTI { get; set; }
        public Nullable<int> ID_QUES { get; set; }
        public string NAM_QUES_OPTI { get; set; }
        public Nullable<int> VAL_QUES_OPTI { get; set; }
    
        public virtual QUESTION QUESTION { get; set; }
    }
}
