//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCE
    {
        public SOURCE()
        {
            this.TICKETs = new HashSet<TICKET>();
        }
    
        public int ID_SOUR { get; set; }
        public string NAM_SOUR { get; set; }
        public string DES_SOUR { get; set; }
        public Nullable<bool> VIG_SOUR { get; set; }
    
        public virtual ICollection<TICKET> TICKETs { get; set; }
    }
}
