//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS
    {
        public STATUS()
        {
            this.QUEUEs = new HashSet<QUEUE>();
            this.TICKETs = new HashSet<TICKET>();
            this.TICKETs1 = new HashSet<TICKET>();
        }
    
        public int ID_STAT { get; set; }
        public string NAM_STAT { get; set; }
        public string NAM_GRAP_STAT { get; set; }
        public string COL_GRAP_STAT { get; set; }
        public string COL_INDV_STAT { get; set; }
        public string DES_STAT { get; set; }
        public Nullable<bool> VIS_STAT { get; set; }
        public Nullable<bool> VIG_STAT { get; set; }
        public string CLA_STAT { get; set; }
        public Nullable<int> ORD_STAT { get; set; }
        public Nullable<bool> VIS_CHAN { get; set; }
        public Nullable<bool> VIS_NEW_TICKET { get; set; }
        public Nullable<bool> DIFERENTIAL { get; set; }
    
        public virtual ICollection<QUEUE> QUEUEs { get; set; }
        public virtual ICollection<TICKET> TICKETs { get; set; }
        public virtual ICollection<TICKET> TICKETs1 { get; set; }
    }
}
