//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_DETAILS_TICKET
    {
        public TYPE_DETAILS_TICKET()
        {
            this.DETAILS_TICKET = new HashSet<DETAILS_TICKET>();
        }
    
        public int ID_TYPE_DETA_TICK { get; set; }
        public string NAM_TYPE_DETA_TICK { get; set; }
        public string DES_TYPE_DETA_TICK { get; set; }
        public Nullable<bool> VIG_TYPE_DETA_TICK { get; set; }
        public Nullable<bool> VIS_TYPE_DETA_TICK { get; set; }
    
        public virtual ICollection<DETAILS_TICKET> DETAILS_TICKET { get; set; }
    }
}
