//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACHED
    {
        public int ID_ATTA { get; set; }
        public string NAM_ATTA { get; set; }
        public string EXT_ATTA { get; set; }
        public Nullable<int> ID_INCI { get; set; }
        public Nullable<int> ID_TRANSACTION { get; set; }
        public Nullable<int> ID_DETA_INCI { get; set; }
        public Nullable<int> ID_ASSE { get; set; }
        public Nullable<int> ID_CLIE_ASSE { get; set; }
        public Nullable<System.DateTime> CREATE_ATTA { get; set; }
        public Nullable<int> ID_ACTI_DOCU_SALE { get; set; }
        public Nullable<int> ID_DOCU_SALE { get; set; }
        public string KEY_ATTA { get; set; }
        public Nullable<int> ID_TYPE_DOCU_ATTA { get; set; }
        public Nullable<bool> DELETE_ATTA { get; set; }
    
        public virtual DETAILS_TICKET DETAILS_TICKET { get; set; }
        public virtual TICKET TICKET { get; set; }
    }
}
