//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public int ID_CATE { get; set; }
        public string NAM_CATE { get; set; }
        public string ACR_CATE { get; set; }
        public string ABR_CATE { get; set; }
        public string DES_CATE { get; set; }
        public Nullable<bool> VIG_CATE { get; set; }
        public Nullable<bool> DEF_CATE { get; set; }
        public Nullable<int> ID_CATE_PARE { get; set; }
        public Nullable<int> NIV_CATE { get; set; }
    }
}
