//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        public QUESTION()
        {
            this.QUESTION_OPTION = new HashSet<QUESTION_OPTION>();
        }
    
        public int ID_QUES { get; set; }
        public Nullable<int> ID_QUES_GROU { get; set; }
        public Nullable<int> ID_QUES_TYPE { get; set; }
        public string NAM_QUES { get; set; }
    
        public virtual ICollection<QUESTION_OPTION> QUESTION_OPTION { get; set; }
        public virtual QUESTION_GROUP QUESTION_GROUP { get; set; }
        public virtual QUESTION_TYPE QUESTION_TYPE { get; set; }
    }
}
