//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_GROUP
    {
        public QUESTION_GROUP()
        {
            this.QUESTIONs = new HashSet<QUESTION>();
        }
    
        public int ID_QUES_GROU { get; set; }
        public Nullable<int> ID_SURVEY { get; set; }
        public string NAM_QUES_GROU { get; set; }
    
        public virtual ICollection<QUESTION> QUESTIONs { get; set; }
        public virtual SURVEY SURVEY { get; set; }
    }
}
