//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY_STATUS
    {
        public SURVEY_STATUS()
        {
            this.SURVEY_TICKET = new HashSet<SURVEY_TICKET>();
        }
    
        public int ID_SURV_STAT { get; set; }
        public string NAM_SURV_STAT { get; set; }
    
        public virtual ICollection<SURVEY_TICKET> SURVEY_TICKET { get; set; }
    }
}
