//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY_TICKET_ACTIVITY
    {
        public int ID_SURV_TICK_ACTI { get; set; }
        public Nullable<int> ID_SURV_TICK { get; set; }
        public Nullable<int> ID_SURV_STAT { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
    
        public virtual SURVEY_TICKET SURVEY_TICKET { get; set; }
    }
}
