//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_SURVEY
    {
        public TYPE_SURVEY()
        {
            this.SURVEYs = new HashSet<SURVEY>();
        }
    
        public int ID_TYPE_SURV { get; set; }
        public string NAM_TYPE_SURV { get; set; }
        public Nullable<bool> VIG_TYPE_SURV { get; set; }
    
        public virtual ICollection<SURVEY> SURVEYs { get; set; }
    }
}
